<template><h1 id="添加声音" tabindex="-1"><a class="header-anchor" href="#添加声音" aria-hidden="true">#</a> 添加声音</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#添加声音-1">添加声音</RouterLink></li></ul></nav>
<h2 id="添加声音-1" tabindex="-1"><a class="header-anchor" href="#添加声音-1" aria-hidden="true">#</a> 添加声音</h2>
<p>使用如下代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> sound <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Sound</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"url to sound file"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">loop</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">autoplay</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.cnbabylon.com/#5GHCDP" target="_blank" rel="noopener noreferrer">添加声音示例<ExternalLinkIcon/></a></p>
<p>让声音只播放一次，使用如下代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> sound <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Sound</span><span class="token punctuation">(</span><span class="token string">"sound"</span><span class="token punctuation">,</span> <span class="token string">"url to sound file"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//Leave time for the sound file to load before playing it</span>
sound<span class="token punctuation">.</span><span class="token function">play</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>考虑到音频的加载时间，在下面的示例中 <strong>setInterval</strong> 用于每 3 秒播放一次声音</p>
<p><a href="https://playground.cnbabylon.com/#B22L51" target="_blank" rel="noopener noreferrer">每3秒播放一次声音<ExternalLinkIcon/></a></p>
<p>接下来，我们会调整建筑物的位置、旋转和缩放。</p>
</template>
