<template><h1 id="创建屋顶" tabindex="-1"><a class="header-anchor" href="#创建屋顶" aria-hidden="true">#</a> 创建屋顶</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#创建屋顶-1">创建屋顶</RouterLink></li></ul></nav>
<h2 id="创建屋顶-1" tabindex="-1"><a class="header-anchor" href="#创建屋顶-1" aria-hidden="true">#</a> 创建屋顶</h2>
<p>使用圆柱创建屋顶，代码如下</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> roof <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateCylinder</span><span class="token punctuation">(</span><span class="token string">"roof"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">diameter</span><span class="token operator">:</span> <span class="token number">1.3</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> <span class="token number">1.2</span><span class="token punctuation">,</span> <span class="token literal-property property">tessellation</span><span class="token operator">:</span> <span class="token number">3</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
roof<span class="token punctuation">.</span>scaling<span class="token punctuation">.</span>x <span class="token operator">=</span> <span class="token number">0.75</span><span class="token punctuation">;</span>
roof<span class="token punctuation">.</span>rotation<span class="token punctuation">.</span>z <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">;</span>
roof<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">1.22</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.cnbabylon.com/#56MSRT" target="_blank" rel="noopener noreferrer">创建屋顶示例<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fhouse1.png&amp;w=1920&amp;q=75" alt=""></p>
</template>
