<template><h1 id="纹理" tabindex="-1"><a class="header-anchor" href="#纹理" aria-hidden="true">#</a> 纹理</h1>
<p>[[toc]</p>
<h2 id="添加纹理" tabindex="-1"><a class="header-anchor" href="#添加纹理" aria-hidden="true">#</a> 添加纹理</h2>
<p>为了给网格添加颜色和纹理，首先需要创建材质</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> material <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>然后，把地面颜色设置为绿色</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> groundMat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"groundMat"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
groundMat<span class="token punctuation">.</span>diffuseColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ground<span class="token punctuation">.</span>material <span class="token operator">=</span> groundMat<span class="token punctuation">;</span> <span class="token comment">//Place the material property of the ground</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>设置颜色需要三个参数，红、绿、蓝(r, g, b) 0 - 1 (0, 0, 0) 是黑色，(1, 1, 1) 是白色。
对于这些颜色，也可以使用</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Red</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Green</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Blue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Black</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>White</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Purple</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Magenta</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Yellow</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Gray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3<span class="token punctuation">.</span>Teal</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面为屋顶和盒子添加纹理</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> roofMat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"roofMat"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
roofMat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"https://assets.babylonjs.com/environments/roof.jpg"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> boxMat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"boxMat"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
boxMat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"https://www.babylonjs-playground.com/textures/floor.png"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最后，将材质指定给网格</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>roof<span class="token punctuation">.</span>material <span class="token operator">=</span> roofMat<span class="token punctuation">;</span>
box<span class="token punctuation">.</span>material <span class="token operator">=</span> boxMat<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.cnbabylon.com/#EL0THL" target="_blank" rel="noopener noreferrer">纹理示例<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fhouse2.png&amp;w=1920&amp;q=75" alt=""></p>
</template>
