<template><h1 id="合并网格" tabindex="-1"><a class="header-anchor" href="#合并网格" aria-hidden="true">#</a> 合并网格</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#使用merge-meshes合并网格">使用Merge Meshes合并网格</RouterLink></li></ul></nav>
<h2 id="使用merge-meshes合并网格" tabindex="-1"><a class="header-anchor" href="#使用merge-meshes合并网格" aria-hidden="true">#</a> 使用Merge Meshes合并网格</h2>
<p>这是合并网格最直接的方式，代码如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> combined <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">MergeMeshes</span><span class="token punctuation">(</span>Array_of_Meshes_to_Combine<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>用在本例中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> house <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">MergeMeshes</span><span class="token punctuation">(</span><span class="token punctuation">[</span>box<span class="token punctuation">,</span> roof<span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.cnbabylon.com/#5FNJZS" target="_blank" rel="noopener noreferrer">合并网格示例<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fhouse5.png&amp;w=1920&amp;q=75" alt=""></p>
<p>现在出现一个问题，整个房子都用了一种材质，屋顶的材质失效了。使用 MergeMes​​hes 的 multiMultiMaterial 参数可以纠正此问题，它是一个长列表中的最后一个参数。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> house <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">MergeMeshes</span><span class="token punctuation">(</span><span class="token punctuation">[</span>box<span class="token punctuation">,</span> roof<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在这个阶段，重要的是要注意，第二个参数为 true（默认） 解构原始网格，最后一个参数为 true 允许将原始材质单独应用于与原始网格匹配的部分。</p>
<p><a href="https://playground.cnbabylon.com/#R0D7ZR" target="_blank" rel="noopener noreferrer">修复合并网格面材质问题示例<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fhouse3.png&amp;w=1920&amp;q=75" alt=""></p>
<p>在复制房子之前，我们需要首先：掌握导出模型的基础知识；如何导入使用 Babylon.js 或其他软件制作的模型；以及如何在自己的网站上展示场景或模型。</p>
</template>
