<template><h1 id="制作副本" tabindex="-1"><a class="header-anchor" href="#制作副本" aria-hidden="true">#</a> 制作副本</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#复制网格">复制网格</RouterLink></li></ul></nav>
<h2 id="复制网格" tabindex="-1"><a class="header-anchor" href="#复制网格" aria-hidden="true">#</a> 复制网格</h2>
<p>复制网格的两种主要方法是克隆或创建实例。克隆提供了一个独立的网格副本，而实例仍然链接到其材质的原始副本。网格实例的材质是无法更改的。</p>
<p>克隆</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>clonedHouse <span class="token operator">=</span> house<span class="token punctuation">.</span><span class="token function">clone</span><span class="token punctuation">(</span><span class="token string">"clonedHouse"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>实例</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>instanceHouse <span class="token operator">=</span> house<span class="token punctuation">.</span><span class="token function">createInstance</span><span class="token punctuation">(</span><span class="token string">"instanceHouse"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在本例中我们不需要改变材质，所以使用实例的方法。我们先将建筑功能结合起来，分别生产宽度为 1 或 2 的房屋，独栋或联排式房子。</p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#77" target="_blank" rel="noopener noreferrer">优化创建建筑物函数示例<ExternalLinkIcon/></a></p>
<p>为了方便查看复制出来的房子，现在扩大一些地面并增加相机半径。首先，为每种类型各建造一所房子并放置到合适的位置。之后，剩余的房子会创建成这两种类型的实例。在决定剩余房子的类型、位置和方向后，使用for循环来创建。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> houses <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>

<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> places<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>places<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">===</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        houses<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> detached_house<span class="token punctuation">.</span><span class="token function">createInstance</span><span class="token punctuation">(</span><span class="token string">"house"</span> <span class="token operator">+</span> i<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">else</span> <span class="token punctuation">{</span>
        houses<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> semi_house<span class="token punctuation">.</span><span class="token function">createInstance</span><span class="token punctuation">(</span><span class="token string">"house"</span> <span class="token operator">+</span> i<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    houses<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>rotation<span class="token punctuation">.</span>y <span class="token operator">=</span> places<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    houses<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>position<span class="token punctuation">.</span>x <span class="token operator">=</span> places<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    houses<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>position<span class="token punctuation">.</span>z <span class="token operator">=</span> places<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KBS9I5#78" target="_blank" rel="noopener noreferrer">创建房子实例示例<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fvillage1.png&amp;w=1920&amp;q=75" alt=""></p>
<p>和以前一样，为了让 Playground 编辑器的上半部分保持更新的代码，我们将把这些房子的建造放到一个函数中。</p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#79" target="_blank" rel="noopener noreferrer">优化创建房子实例示例<ExternalLinkIcon/></a></p>
<p>现在我们正在构建的世界有点复杂，可以把模型下载下来，然后以导入模型的方式重新加载。</p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#80" target="_blank" rel="noopener noreferrer">加载村庄模型示例<ExternalLinkIcon/></a></p>
</template>
