<template><h1 id="更改查看器视图相机" tabindex="-1"><a class="header-anchor" href="#更改查看器视图相机" aria-hidden="true">#</a> 更改查看器视图相机</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#更改查看器视图相机-1">更改查看器视图相机</RouterLink></li></ul></nav>
<h2 id="更改查看器视图相机-1" tabindex="-1"><a class="header-anchor" href="#更改查看器视图相机-1" aria-hidden="true">#</a> 更改查看器视图相机</h2>
<p>把村庄作为模型放入查看器时会发生什么？</p>
<p>使用默认视图的<a href="https://doc.babylonjs.com/webpages/page2.html" target="_blank" rel="noopener noreferrer">村庄场景<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fview2.png&amp;w=1920&amp;q=75" alt=""></p>
<p>可以看到地面在闪烁。这是为什么？这是因为默认情况下，查看器已经添加了一个地面，在它们重叠的地方两者会出现这种闪烁。</p>
<p>我们如何克服这一点？我们在 <code v-pre>&lt;babylon&gt;</code> 元素中使用 <strong>extends</strong> 属性并将其设置为最小。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>babylon <span class="token keyword">extends</span><span class="token operator">=</span><span class="token string">"minimal"</span> model<span class="token operator">=</span><span class="token string">"path to model file"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>babylon<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>这会删除默认地面及其他东西，例如 Babylon.js 链接和全屏图标</p>
<p>使用精简查看器的<a href="https://doc.babylonjs.com/webpages/page3.html" target="_blank" rel="noopener noreferrer">村庄场景<ExternalLinkIcon/></a></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fview3.png&amp;w=1920&amp;q=75" alt=""></p>
<p>删除默认地面已停止闪烁。然而，默认查看器会计算模型的范围并相应地调整相机。由于使用<em>minimal</em>精简查看器，相机默认设置为靠近模型村庄的中心。</p>
<p>现在相机太近了，如果想要相机更远此，就必须用一些代码实现。</p>
<p>要移动相机，必须调整它的半径属性。这必须在加载模型<strong>之前</strong>完成。一旦在查看器中加载了模型，就无法更改属性。我们需要从 <code v-pre>&lt;babylon&gt;</code> 元素中删除模型<em>model</em>属性，以防止在更改相机半径之前加载模型。 <code v-pre>&lt;babylon&gt;</code> 元素还必须被赋予一个 <strong>id</strong>，该 id 会在改变相机属性的脚本中引用。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>babylon id<span class="token operator">=</span><span class="token string">"myViewer"</span> <span class="token keyword">extends</span><span class="token operator">=</span><span class="token string">"minimal"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>babylon<span class="token operator">></span> <span class="token comment">// 一个精简版查看器，增加了id，去掉了model属性</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>以下代码设置相机半径（在本例中为俯角），然后使用加载模型</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
    BabylonViewer<span class="token punctuation">.</span>viewerManager<span class="token punctuation">.</span><span class="token function">getViewerPromiseById</span><span class="token punctuation">(</span><span class="token string">'myViewer'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">viewer</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        viewer<span class="token punctuation">.</span>onSceneInitObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            viewer<span class="token punctuation">.</span>sceneManager<span class="token punctuation">.</span>camera<span class="token punctuation">.</span>radius <span class="token operator">=</span> <span class="token number">15</span><span class="token punctuation">;</span> <span class="token comment">//set camera radius</span>
            viewer<span class="token punctuation">.</span>sceneManager<span class="token punctuation">.</span>camera<span class="token punctuation">.</span>beta <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2.2</span><span class="token punctuation">;</span> <span class="token comment">//angle of depression</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        viewer<span class="token punctuation">.</span>onEngineInitObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            viewer<span class="token punctuation">.</span><span class="token function">loadModel</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"path to model file"</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>调整相机后的<a href="https://doc.babylonjs.com/webpages/page4" target="_blank" rel="noopener noreferrer">村庄场景<ExternalLinkIcon/></a></p>
<p>在开发 Web 游戏或应用程序时，会需要比查看器更加灵活的方式。让我们再看看如何使用 <strong>HTML</strong> 模板。</p>
</template>
