<template><h1 id="网格行为" tabindex="-1"><a class="header-anchor" href="#网格行为" aria-hidden="true">#</a> 网格行为</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#简介">简介</RouterLink></li><li><RouterLink to="#指针拖动行为-pointerdragbehavior">指针拖动行为 PointerDragBehavior</RouterLink></li><li><RouterLink to="#_6自由度拖动行为-sixdofdragbehavior">6自由度拖动行为 SixDofDragBehavior</RouterLink></li><li><RouterLink to="#多点缩放行为-multipointerscalebehavior">多点缩放行为 MultiPointerScaleBehavior</RouterLink></li><li><RouterLink to="#附加盒子行为-attachtoboxbehavior-appbar">附加盒子行为 AttachToBoxBehavior (AppBar)</RouterLink></li><li><RouterLink to="#跟随行为-followbehavior">跟随行为 FollowBehavior</RouterLink></li><li><RouterLink to="#表面吸附行为-surfacemagnetismbehavior">表面吸附行为 SurfaceMagnetismBehavior</RouterLink></li><li><RouterLink to="#手部约束行为-handconstraintbehavior">手部约束行为 HandConstraintBehavior</RouterLink></li></ul></nav>
<h2 id="简介" tabindex="-1"><a class="header-anchor" href="#简介" aria-hidden="true">#</a> 简介</h2>
<p>网格行为是可以附加到网格的<RouterLink to="/babylonjs/divingDeeper/behaviors/">行为</RouterLink>。</p>
<h2 id="指针拖动行为-pointerdragbehavior" tabindex="-1"><a class="header-anchor" href="#指针拖动行为-pointerdragbehavior" aria-hidden="true">#</a> 指针拖动行为 PointerDragBehavior</h2>
<p>用于使用鼠标或 VR 控制器围绕平面或轴拖动网格。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> pointerDragBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>PointerDragBehavior</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">dragAxis</span><span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 沿Y轴拖动</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>它可以在 3 种不同模式下初始化</p>
<ul>
<li>dragAxis: 将沿提供的轴进行拖动</li>
<li>dragPlaneNormal: 将沿法线定义的平面拖动</li>
<li>None: 将沿面向相机的平面进行拖动</li>
</ul>
<p>默认情况下，拖动平面/轴将根据物体方向进行修改。要将指定的轴/平面固定到世界，请将其设置为 false。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>pointerDragBehavior<span class="token punctuation">.</span>useObjectOrientationForDragging <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span> <span class="token comment">// 由自身坐标修改为世界坐标</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>默认情况下，拖动平面将在每一帧更新，禁用此设置可将 <strong>updateDragPlane</strong> 设为 <strong>false</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>pointerDragBehavior<span class="token punctuation">.</span>updateDragPlane <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>要监听拖动事件，可以使用以下代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>pointerDragBehavior<span class="token punctuation">.</span>onDragStartObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"dragStart"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
pointerDragBehavior<span class="token punctuation">.</span>onDragObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"drag"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
pointerDragBehavior<span class="token punctuation">.</span>onDragEndObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"dragEnd"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>要在不移动网格的情况下使用拖动行为，请将其设置为 false。然后可以监听上面的拖动事件以允许自定义拖动交互。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>pointerDragBehavior<span class="token punctuation">.</span>moveAttached <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span> <span class="token comment">// 网格不受拖动行为影响</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>要禁用所有拖动行为，请将 <strong>enabled</strong> 设置为 <strong>false</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>pointerDragBehavior<span class="token punctuation">.</span>enabled <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>要检查拖动网格的当前状态，可以检查 currentDraggingPointerID、dragging 和 lastDragPosition</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// The id of the pointer that is currently interacting with the behavior (-1 when no pointer is active)</span>
pointerDragBehavior<span class="token punctuation">.</span>currentDraggingPointerID<span class="token punctuation">;</span>
<span class="token comment">// The last position where the pointer hit the drag plane in world space</span>
pointerDragBehavior<span class="token punctuation">.</span>lastDragPosition<span class="token punctuation">;</span>
<span class="token comment">// If the behavior is currently in a dragging state</span>
pointerDragBehavior<span class="token punctuation">.</span>dragging<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#YEZPVT" target="_blank" rel="noopener noreferrer">沿轴拖动示例<ExternalLinkIcon/></a></p>
<h2 id="_6自由度拖动行为-sixdofdragbehavior" tabindex="-1"><a class="header-anchor" href="#_6自由度拖动行为-sixdofdragbehavior" aria-hidden="true">#</a> 6自由度拖动行为 SixDofDragBehavior</h2>
<p>用于根据指针原点（例如相机或 vr 控制器位置）在 3D 空间中拖动网格</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> sixDofDragBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SixDofDragBehavior</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>默认情况下，通过将网格缓慢移动到指针指向的位置来平滑指针抖动。要删除或修改此行为，可以修改以下字段。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// The distance towards the target drag position to move each frame. This can be useful to avoid jitter. Set this to 1 for no delay. (Default: 0.2)</span>
sixDofDragBehavior<span class="token punctuation">.</span>dragDeltaRatio <span class="token operator">=</span> <span class="token number">0.2</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>默认情况下，拖动物体远离或朝向用户的距离会被放大，以使移动较远距离时更容易。为避免或修改此效果，可以使用以下操作。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// The distance towards the target drag position to move each frame. This can be useful to avoid jitter. Set this to 1 for no delay. (Default: 0.2)</span>
sixDofDragBehavior<span class="token punctuation">.</span>zDragFactor <span class="token operator">=</span> <span class="token number">0.2</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>注 - 要避免使用复杂模型时造成的性能消耗，模型应包裹在边界盒bounding box网格中。查看<a href="https://doc.babylonjs.com/divingDeeper/mesh/gizmo" target="_blank" rel="noopener noreferrer">bundingboxgizmo.makenotpickableandwrapinboundingbox<ExternalLinkIcon/></a>.</p>
<p><a href="https://playground.babylonjs.com/#5G9MC5" target="_blank" rel="noopener noreferrer">6自由度示例<ExternalLinkIcon/></a></p>
<h2 id="多点缩放行为-multipointerscalebehavior" tabindex="-1"><a class="header-anchor" href="#多点缩放行为-multipointerscalebehavior" aria-hidden="true">#</a> 多点缩放行为 MultiPointerScaleBehavior</h2>
<p>用于使用 2 个指针（例如双指或 VR 控制器）缩放网格</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> multiPointerScaleBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>MultiPointerScaleBehavior</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>注 - 要避免使用复杂模型时造成的性能消耗，模型应包裹在边界盒bounding box网格中。查看<a href="https://doc.babylonjs.com/divingDeeper/mesh/gizmo" target="_blank" rel="noopener noreferrer">bundingboxgizmo.makenotpickableandwrapinboundingbox<ExternalLinkIcon/></a>.</p>
<p><a href="https://playground.babylonjs.com/#5G9MC5" target="_blank" rel="noopener noreferrer">多点缩放行为示例<ExternalLinkIcon/></a></p>
<h2 id="附加盒子行为-attachtoboxbehavior-appbar" tabindex="-1"><a class="header-anchor" href="#附加盒子行为-attachtoboxbehavior-appbar" aria-hidden="true">#</a> 附加盒子行为 AttachToBoxBehavior (AppBar)</h2>
<p>用于在网格边界盒顶部附加网格或UI</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> behavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>AttachToBoxBehavior</span><span class="token punctuation">(</span>appBar<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// appBar是一个TransformNode</span>
boundingBox<span class="token punctuation">.</span><span class="token function">addBehavior</span><span class="token punctuation">(</span>behavior<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>调节附加网格的位置，使用</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>behavior<span class="token punctuation">.</span>distanceAwayFromFace <span class="token operator">=</span> <span class="token number">0.15</span><span class="token punctuation">;</span> <span class="token comment">// 距离表面</span>
behavior<span class="token punctuation">.</span>distanceAwayFromBottomOfFace <span class="token operator">=</span> <span class="token number">0.15</span><span class="token punctuation">;</span> <span class="token comment">// 距离底部</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>可用于将应用条附加到网格，见<a href="https://playground.babylonjs.com/#X6MQ1L" target="_blank" rel="noopener noreferrer">示例<ExternalLinkIcon/></a>。</p>
<h2 id="跟随行为-followbehavior" tabindex="-1"><a class="header-anchor" href="#跟随行为-followbehavior" aria-hidden="true">#</a> 跟随行为 FollowBehavior</h2>
<p>用于使网格跟随相机。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> followBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>FollowBehavior</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
followBehavior<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span>mesh<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>网格的位置/旋转将在 3 种情况下更新：</p>
<ul>
<li>要么网格超出视野范围。使用 <strong>maxViewVerticalDegrees</strong> 和 <strong>maxViewHorizo​​ntalDegrees</strong> 来调整这些边界。</li>
<li>网格离相机太近或太远。使用 <strong>defaultDistance</strong>、<strong>minimumDistance</strong> 和 <strong>maximumDistance</strong> 来调整这些距离。</li>
<li>要么网格背对相机。使用 <strong>orientToCameraDeadzoneDegrees</strong> 来界定网格可以背对的最大角度。</li>
</ul>
<p>在 XR 体验中，不考虑用户头部的完整旋转会很有用。使用属性 <strong>ignoreCameraPitchAndRoll</strong> 仅考虑头部的偏航（绕 Y 轴旋转）。在此模式下，可以使用 <strong>pitchOffset</strong> 将网格稍微放置在水平面下方或上方。</p>
<p>与 SixDofDragBehavior 一样，网格的每个变换都通过插值以避免抖动。使用 <strong>lerpTime</strong> 调整插值的长度（越高越慢）。</p>
<h2 id="表面吸附行为-surfacemagnetismbehavior" tabindex="-1"><a class="header-anchor" href="#表面吸附行为-surfacemagnetismbehavior" aria-hidden="true">#</a> 表面吸附行为 SurfaceMagnetismBehavior</h2>
<p>用于使网格粘在另一个网格上，并沿其法线定向。例如，它可以用于 XR 体验，使 UI 控件贴在墙上。</p>
<p><strong>meshes</strong> 属性是准备用于相交的网格列表。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> surfaceMagnetismBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SurfaceMagnetismBehavior</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
surfaceMagnetismBehavior<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span>mesh<span class="token punctuation">)</span><span class="token punctuation">;</span>
surfaceMagnetismBehavior<span class="token punctuation">.</span>meshes <span class="token operator">=</span> meshes<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>默认情况下，每次指针移动时它都会与网格相交，并且位置将相应地更新（使用插值，就像使用 FollowBehavior）。使用 <strong>enabled</strong> 来控制此行为是否开启。</p>
<h2 id="手部约束行为-handconstraintbehavior" tabindex="-1"><a class="header-anchor" href="#手部约束行为-handconstraintbehavior" aria-hidden="true">#</a> 手部约束行为 HandConstraintBehavior</h2>
<p>用于使网格跟随用户的手。它应始终链接到 <strong>WebXRDefaultExperience</strong> 以检索手的位置。 XR 体验还应启用 <strong>HandTracking</strong> 功能，如下所示：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>xr<span class="token punctuation">.</span>baseExperience<span class="token punctuation">.</span>featuresManager<span class="token punctuation">.</span><span class="token function">enableFeature</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>WebXRFeatureName<span class="token punctuation">.</span><span class="token constant">HAND_TRACKING</span><span class="token punctuation">,</span> <span class="token string">"latest"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">xrInput</span><span class="token operator">:</span> xr<span class="token punctuation">.</span>input
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后可以实例化行为，将其附加到网格，并将其链接到 XR 体验：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> handConstraintBehavior <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HandConstraintBehavior</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
handConstraintBehavior<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span>mesh<span class="token punctuation">)</span><span class="token punctuation">;</span>
handConstraintBehavior<span class="token punctuation">.</span><span class="token function">linkToXRExperience</span><span class="token punctuation">(</span>xr<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通过 <strong>handedness</strong> 属性可以改变要跟随的手。</p>
</template>
