<template><h1 id="网格相交-mesh-intersections" tabindex="-1"><a class="header-anchor" href="#网格相交-mesh-intersections" aria-hidden="true">#</a> 网格相交 Mesh Intersections</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#网格碰撞-collisions">网格碰撞 Collisions</RouterLink></li><li><RouterLink to="#如何实现">如何实现？</RouterLink><ul><li><RouterLink to="#与网格相交-intersectsmesh">与网格相交 intersectsMesh</RouterLink></li><li><RouterLink to="#与点相交-intersectspoint">与点相交 intersectsPoint</RouterLink></li></ul></li></ul></nav>
<h2 id="网格碰撞-collisions" tabindex="-1"><a class="header-anchor" href="#网格碰撞-collisions" aria-hidden="true">#</a> 网格碰撞 Collisions</h2>
<p>在动态场景中，物体在移动并相互交叉。为了获得最佳的渲染效果，你会想知道网格是什么时候相互接触的。在本教程中，我们将发现碰撞系统是如何工作的。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FCollisions%20Intersect%2F10.png&amp;w=1920&amp;q=75" alt=""></p>
<h2 id="如何实现" tabindex="-1"><a class="header-anchor" href="#如何实现" aria-hidden="true">#</a> 如何实现？</h2>
<p>本教程将向你展示两种碰撞检测的方法：第一种是在两个网格接触时引发碰撞事件，另一种是检测一个网格和一个点的接触。</p>
<p>我们要讨论的是上面的场景。第一和第二个的球体将与旋转的地面发生碰撞，最后一个的球体将与一个点上发生碰撞。</p>
<p><a href="https://playground.babylonjs.com/#KQV9SA" target="_blank" rel="noopener noreferrer">网格碰撞示例<ExternalLinkIcon/></a></p>
<h3 id="与网格相交-intersectsmesh" tabindex="-1"><a class="header-anchor" href="#与网格相交-intersectsmesh" aria-hidden="true">#</a> 与网格相交 intersectsMesh</h3>
<p>这里的重点是检测球体和地面之间的接触。我们将使用 <code v-pre>intersectsMesh()</code> 函数，它有两个参数：要检测的网格和相交的精度（布尔值）。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>balloon1<span class="token punctuation">.</span><span class="token function">intersectsMesh</span><span class="token punctuation">(</span>plan1<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  balloon1<span class="token punctuation">.</span>material<span class="token punctuation">.</span>emissiveColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
  balloon1<span class="token punctuation">.</span>material<span class="token punctuation">.</span>emissiveColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为了避免因检测网格上的过多细节造成昂贵的计算，Babylon引擎在物体周围创建一个边界盒boundingBox，并检测边界盒与碰撞网格之间的交集。下面是一个边界盒的例子：</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FCollisions%20Intersect%2F10-1.png&amp;w=1920&amp;q=75" alt=""></p>
<p>但是这个边界盒可以更精确或更不精确，这就是为什么我们有第二个参数。简而言之，如果这个参数设置为 &quot;true&quot;（默认为 &quot;false&quot;），那么这个边界盒就会更接近于网格（OBB边界类型），但它的计算成本更高。注意，当网格旋转到一个角度时，这种类型的边界盒特别有用。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FCollisions%20Intersect%2F10-2.png&amp;w=1920&amp;q=75" alt=""></p>
<p>因此，在选择之前要考虑到你需要的碰撞细节。</p>
<p>如果你想了解这第二个参数的更多信息，可以看看维基百科的这个页面，特别是关于AABB和OBB模式：<a href="https://en.wikipedia.org/wiki/Bounding_volume" target="_blank" rel="noopener noreferrer">https://en.wikipedia.org/wiki/Bounding_volume<ExternalLinkIcon/></a></p>
<h3 id="与点相交-intersectspoint" tabindex="-1"><a class="header-anchor" href="#与点相交-intersectspoint" aria-hidden="true">#</a> 与点相交 intersectsPoint</h3>
<p>另一个函数是<code v-pre>intersectsPoint()</code>，与一个特定的点相交，代码如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> pointToIntersect <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>balloon3<span class="token punctuation">.</span><span class="token function">intersectsPoint</span><span class="token punctuation">(</span>pointToIntersect<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  balloon3<span class="token punctuation">.</span>material<span class="token punctuation">.</span>emissiveColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们在场景中定义了一个精确的点，如果球体与这个点相交，无论在球体的什么地方，事件就会被触发，从而改变球体的颜色。</p>
</template>
