<template><h1 id="粒子喷泉" tabindex="-1"><a class="header-anchor" href="#粒子喷泉" aria-hidden="true">#</a> 粒子喷泉</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>粒子是在集群或云中发射的小精灵，用于模拟火、烟、水甚至浮尘。</p>
<p>粒子云的基础是粒子系统。有了这个，我们指定要使用的粒子数</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> particleSystem <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ParticleSystem</span><span class="token punctuation">(</span><span class="token string">"particles"</span><span class="token punctuation">,</span> <span class="token number">5000</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">//scene is optional</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>粒子从特定定义的区域发射。每个粒子都有一个生命周期，当生命结束时，它会被重复使用并重新发射。</p>
<p>它们被赋予一种纹理，这显然决定了它们的外观，</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>particleTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"url to image"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>基本发射器区域是一个围绕指定点的给定尺寸的盒子；</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>emitter <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">0.8</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// the point at the top of the fountain</span>
particleSystem<span class="token punctuation">.</span>minEmitBox <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">0.01</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">0.01</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// minimum box dimensions</span>
particleSystem<span class="token punctuation">.</span>maxEmitBox <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0.01</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.01</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// maximum box dimensions</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最多可以以 (r, g, b, a) 形式为红色、绿色、蓝色和 alpha 提供三种颜色。 Alpha 从 0 表示完全透明到 1 表示完全不透明。前两个组合或混合以设置粒子的颜色。可以指定混合方法。第三个具有属性 colorDead 并且在粒子回收设置为关闭时有用。我们的喷泉不需要这第三个属性。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>color1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">0.7</span><span class="token punctuation">,</span> <span class="token number">0.8</span><span class="token punctuation">,</span> <span class="token number">1.0</span><span class="token punctuation">,</span> <span class="token number">1.0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>color2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">0.2</span><span class="token punctuation">,</span> <span class="token number">0.5</span><span class="token punctuation">,</span> <span class="token number">1.0</span><span class="token punctuation">,</span> <span class="token number">1.0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

particleSystem<span class="token punctuation">.</span>blendMode <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>ParticleSystem<span class="token punctuation">.</span><span class="token constant">BLENDMODE_ONEONE</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>粒子的大小及其寿命在最小值和最大值设定的范围内。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>minSize <span class="token operator">=</span> <span class="token number">0.01</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>maxSize <span class="token operator">=</span> <span class="token number">0.05</span><span class="token punctuation">;</span>

particleSystem<span class="token punctuation">.</span>minLifeTime <span class="token operator">=</span> <span class="token number">0.3</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>maxLifeTime <span class="token operator">=</span> <span class="token number">1.5</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们还需要设置每秒发射的粒子数。长寿命的发射率太快会导致粒子发射出现间隙。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>emitRate <span class="token operator">=</span> <span class="token number">1500</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>我们还为粒子设置了两个可能的方向，并通过给出最小和最大功率值以及更新速度来影响粒子行进的速度。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>direction1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>direction2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

particleSystem<span class="token punctuation">.</span>minEmitPower <span class="token operator">=</span> <span class="token number">0.2</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>maxEmitPower <span class="token operator">=</span> <span class="token number">0.6</span><span class="token punctuation">;</span>
particleSystem<span class="token punctuation">.</span>updateSpeed <span class="token operator">=</span> <span class="token number">0.01</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在 y 分量中为 graving 设置负值可确保粒子向下落。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span>gravity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">9.81</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>最后可以开始喷泉了</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>particleSystem<span class="token punctuation">.</span><span class="token function">start</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#TC31NV#4" target="_blank" rel="noopener noreferrer">粒子喷泉<ExternalLinkIcon/></a></p>
</template>
