<template><h1 id="资产管理器-assetmanager" tabindex="-1"><a class="header-anchor" href="#资产管理器-assetmanager" aria-hidden="true">#</a> 资产管理器 AssetManager</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#使用场景">使用场景</RouterLink></li><li><RouterLink to="#assetsmanager-用法">AssetsManager 用法</RouterLink><ul><li><RouterLink to="#初始化和创建任务">初始化和创建任务</RouterLink></li><li><RouterLink to="#任务状态和错误处理">任务状态和错误处理</RouterLink></li><li><RouterLink to="#管理器回调和观察器">管理器回调和观察器</RouterLink></li><li><RouterLink to="#执行任务">执行任务</RouterLink></li></ul></li><li><RouterLink to="#可用任务">可用任务</RouterLink><ul><li><RouterLink to="#meshassettask">MeshAssetTask</RouterLink></li><li><RouterLink to="#textfileassettask">TextFileAssetTask</RouterLink></li><li><RouterLink to="#binaryfileassettask">BinaryFileAssetTask</RouterLink></li><li><RouterLink to="#imageassettask">ImageAssetTask</RouterLink></li><li><RouterLink to="#textureassettask">TextureAssetTask</RouterLink></li><li><RouterLink to="#cubetextureassettask">CubeTextureAssetTask</RouterLink></li><li><RouterLink to="#hdrcubetextureassettask">HDRCubeTextureAssetTask</RouterLink></li><li><RouterLink to="#equirectangularcubetextureassettask">EquiRectangularCubeTextureAssetTask</RouterLink></li></ul></li><li><RouterLink to="#使用加载界面">使用加载界面</RouterLink></li><li><RouterLink to="#笔记">笔记</RouterLink></li></ul></nav>
<h2 id="使用场景" tabindex="-1"><a class="header-anchor" href="#使用场景" aria-hidden="true">#</a> 使用场景</h2>
<p>为了帮助开发者加载多个资产，Babylon.js（从1.14版本开始）引入了 AssetsManager 类。这个类可以用来将网格导入场景或加载文本和二进制文件。</p>
<p>注意：由于导入的网格会有一个 rotationQuaternion 设置，对一个网格应用旋转将产生不可预知的后果，详见<a href="https://doc.babylonjs.com/divingDeeper/mesh/transforms/center_origin/rotation_conventions" target="_blank" rel="noopener noreferrer">本警告<ExternalLinkIcon/></a>。</p>
<h2 id="assetsmanager-用法" tabindex="-1"><a class="header-anchor" href="#assetsmanager-用法" aria-hidden="true">#</a> AssetsManager 用法</h2>
<h3 id="初始化和创建任务" tabindex="-1"><a class="header-anchor" href="#初始化和创建任务" aria-hidden="true">#</a> 初始化和创建任务</h3>
<p>要使用它，只需要以当前场景为参数实例化一个：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> assetsManager <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>AssetsManager</span><span class="token punctuation">(</span>scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>然后，可以向管理器添加任务：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> meshTask <span class="token operator">=</span> assetsManager<span class="token punctuation">.</span><span class="token function">addMeshTask</span><span class="token punctuation">(</span><span class="token string">"skull task"</span><span class="token punctuation">,</span> <span class="token string">""</span><span class="token punctuation">,</span> <span class="token string">"scenes/"</span><span class="token punctuation">,</span> <span class="token string">"skull.babylon"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>每个任务都会提供一个 <code v-pre>onSuccess</code> 和 <code v-pre>onError</code> 回调：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>meshTask<span class="token punctuation">.</span><span class="token function-variable function">onSuccess</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    task<span class="token punctuation">.</span>loadedMeshes<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Zero</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>meshTask<span class="token punctuation">.</span><span class="token function-variable function">onError</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">task<span class="token punctuation">,</span> message<span class="token punctuation">,</span> exception</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> exception<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>文本和二进制文件</strong>通过 <code v-pre>addTextFileTask</code> 和 <code v-pre>addBinaryFileTask</code> 方法支持：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> textTask <span class="token operator">=</span> assetsManager<span class="token punctuation">.</span><span class="token function">addTextFileTask</span><span class="token punctuation">(</span><span class="token string">"text task"</span><span class="token punctuation">,</span> <span class="token string">"msg.txt"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
textTask<span class="token punctuation">.</span><span class="token function-variable function">onSuccess</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>task<span class="token punctuation">.</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">var</span> binaryTask <span class="token operator">=</span> assetsManager<span class="token punctuation">.</span><span class="token function">addBinaryFileTask</span><span class="token punctuation">(</span><span class="token string">"binary task"</span><span class="token punctuation">,</span> <span class="token string">"grass.jpg"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
binaryTask<span class="token punctuation">.</span><span class="token function-variable function">onSuccess</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// Do something with task.data</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>图片</strong>通过 <code v-pre>addImageTask</code> 方法支持：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> imageTask <span class="token operator">=</span> assetsManager<span class="token punctuation">.</span><span class="token function">addImageTask</span><span class="token punctuation">(</span><span class="token string">"image task"</span><span class="token punctuation">,</span> <span class="token string">"img.jpg"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
imageTask<span class="token punctuation">.</span><span class="token function-variable function">onSuccess</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>task<span class="token punctuation">.</span>image<span class="token punctuation">.</span>width<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>纹理</strong>通过 <code v-pre>addTextureTask</code> 方法支持：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> textureTask <span class="token operator">=</span> assetsManager<span class="token punctuation">.</span><span class="token function">addTextureTask</span><span class="token punctuation">(</span><span class="token string">"image task"</span><span class="token punctuation">,</span> <span class="token string">"img.jpg"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
textureTask<span class="token punctuation">.</span><span class="token function-variable function">onSuccess</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    material<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> task<span class="token punctuation">.</span>texture<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="任务状态和错误处理" tabindex="-1"><a class="header-anchor" href="#任务状态和错误处理" aria-hidden="true">#</a> 任务状态和错误处理</h3>
<p>每个任务都有一个状态对象，代表任务的当前执行状态。该状态由一个枚举表示，<code v-pre>BABYLON.AssetTaskState</code>，有4种状态。</p>
<ul>
<li>INIT - 任务开始执行前</li>
<li>RUNNING - 当任务开始执行但还没有完成时</li>
<li>DONE - 当任务成功完成执行时</li>
<li>ERROR - 当任务失败时</li>
</ul>
<p>如果一个任务有错误状态（<code v-pre>BABYLON.AssetTaskState.ERROR</code>），一个新的对象将被添加到该任务中：<code v-pre>task.errorObject</code>。错误对象定义了2个变量，都是可选的：</p>
<ul>
<li>message - 简短解释错误的字符串（例如“请求返回 404”）</li>
<li>exception - 如果在执行过程中抛出了一个异常，异常对象将包含堆栈跟踪信息</li>
</ul>
<p>这样，在使用资产管理器观察者时也可以访问错误：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span>onTaskErrorObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'task failed'</span><span class="token punctuation">,</span> task<span class="token punctuation">.</span>errorObject<span class="token punctuation">.</span>message<span class="token punctuation">,</span> task<span class="token punctuation">.</span>errorObject<span class="token punctuation">.</span>exception<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="管理器回调和观察器" tabindex="-1"><a class="header-anchor" href="#管理器回调和观察器" aria-hidden="true">#</a> 管理器回调和观察器</h3>
<p>管理器自身提供了4个回调：</p>
<ul>
<li>onFinish</li>
<li>onProgress</li>
<li>onTaskSuccess</li>
<li>onTaskError</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span><span class="token function-variable function">onProgress</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">remainingCount<span class="token punctuation">,</span> totalCount<span class="token punctuation">,</span> lastFinishedTask</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    engine<span class="token punctuation">.</span>loadingUIText <span class="token operator">=</span> <span class="token string">'We are loading the scene. '</span> <span class="token operator">+</span> remainingCount <span class="token operator">+</span> <span class="token string">' out of '</span> <span class="token operator">+</span> totalCount <span class="token operator">+</span> <span class="token string">' items still need to be loaded.'</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

assetsManager<span class="token punctuation">.</span><span class="token function-variable function">onFinish</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">tasks</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    engine<span class="token punctuation">.</span><span class="token function">runRenderLoop</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        scene<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>管理器还允许你使用观察者 observer，以处理onFinish、onProgress、onTaskSuccess和onTaskError：</p>
<ul>
<li>onTaskSuccessObservable - 当一个任务成功完成时，注册的观察者将被执行。</li>
<li>onTaskErrorObservable - 当一个任务失败时，注册的观察者将被执行。</li>
<li>onProgressObservable - 当一个任务成功或失败时，注册的观察者将被执行。</li>
<li>onTasksDoneObservable - 当所有任务执行完毕（成功或失败！）时，注册的观察者将被执行。</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span>onTaskSuccessObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'task successful'</span><span class="token punctuation">,</span> task<span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span>onTasksDoneObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">tasks</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> errors <span class="token operator">=</span> tasks<span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token keyword">return</span> task<span class="token punctuation">.</span>taskState <span class="token operator">===</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>AssetTaskState<span class="token punctuation">.</span><span class="token constant">ERROR</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">var</span> successes <span class="token operator">=</span> tasks<span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token keyword">return</span> task<span class="token punctuation">.</span>taskState <span class="token operator">!==</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>AssetTaskState<span class="token punctuation">.</span><span class="token constant">ERROR</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="执行任务" tabindex="-1"><a class="header-anchor" href="#执行任务" aria-hidden="true">#</a> 执行任务</h3>
<p>要执行所有任务，使用如下代码：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span><span class="token function">load</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://www.babylonjs.com/scenes/assets" target="_blank" rel="noopener noreferrer">资产加载示例<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#ZJYNY#0" target="_blank" rel="noopener noreferrer">Playground示例<ExternalLinkIcon/></a></p>
<h2 id="可用任务" tabindex="-1"><a class="header-anchor" href="#可用任务" aria-hidden="true">#</a> 可用任务</h2>
<p>使用资产管理器可以执行 8 种类型的任务。</p>
<p>每个任务都使用以下属性扩展 <code v-pre>AbstractAssetTask</code> 类（并实现 <code v-pre>IAssetTask</code> 接口）：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function-variable function">onSuccess</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> IAssetTask<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
<span class="token function-variable function">onError</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> IAssetTask<span class="token punctuation">,</span> message<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> exception<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>

isCompleted<span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
taskState<span class="token operator">:</span> AssetTaskState<span class="token punctuation">;</span>
errorObject<span class="token operator">:</span> <span class="token punctuation">{</span> message<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span> exception<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">;</span> <span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>注意，初始化一个任务所需的属性总是与它所创建的对象类型相对应。例如，<code v-pre>CubeTextureAssetTask</code> 的构造函数签名需要与 <code v-pre>BABYLON.CubeTexture</code> 类有相同的变量。变量的顺序可能有所不同。</p>
<h3 id="meshassettask" tabindex="-1"><a class="header-anchor" href="#meshassettask" aria-hidden="true">#</a> MeshAssetTask</h3>
<p>MeshAssetTask 用于从外部加载模型（.babylon, .obj, .gltf等）。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> meshesNames<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> rootUrl<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> sceneFilename<span class="token operator">:</span> <span class="token builtin">string</span> <span class="token operator">|</span> File<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> loadedMeshes<span class="token operator">:</span> <span class="token builtin">Array</span><span class="token operator">&lt;</span>AbstractMesh<span class="token operator">></span><span class="token punctuation">;</span>
<span class="token keyword">public</span> loadedParticleSystems<span class="token operator">:</span> <span class="token builtin">Array</span><span class="token operator">&lt;</span>ParticleSystem<span class="token operator">></span><span class="token punctuation">;</span>
<span class="token keyword">public</span> loadedSkeletons<span class="token operator">:</span> <span class="token builtin">Array</span><span class="token operator">&lt;</span>Skeleton<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="textfileassettask" tabindex="-1"><a class="header-anchor" href="#textfileassettask" aria-hidden="true">#</a> TextFileAssetTask</h3>
<p>用于异步加载（文本）文件。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
<span class="token keyword">public</span> text<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="binaryfileassettask" tabindex="-1"><a class="header-anchor" href="#binaryfileassettask" aria-hidden="true">#</a> BinaryFileAssetTask</h3>
<p>这个任务用来加载一个二进制文件。它与 TextFileAssetTask 的主要区别是，数据将被存储在一个 <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer" target="_blank" rel="noopener noreferrer">ArrayBuffer<ExternalLinkIcon/></a> 中。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
<span class="token keyword">public</span> data<span class="token operator">:</span> ArrayBuffer<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="imageassettask" tabindex="-1"><a class="header-anchor" href="#imageassettask" aria-hidden="true">#</a> ImageAssetTask</h3>
<p>这个方法将加载一张图片（.png, .jpg, .gif）。它将创建一个<a href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement" target="_blank" rel="noopener noreferrer">HTMLImageElement<ExternalLinkIcon/></a>对象。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
<span class="token keyword">public</span> image<span class="token operator">:</span> HTMLImageElement<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="textureassettask" tabindex="-1"><a class="header-anchor" href="#textureassettask" aria-hidden="true">#</a> TextureAssetTask</h3>
<p>这将从提供的单个URL中创建一个新的BABYLON.Texture。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> noMipmap<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">boolean</span><span class="token punctuation">,</span> invertY<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">boolean</span><span class="token punctuation">,</span> samplingMode<span class="token operator">:</span> <span class="token builtin">number</span> <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Texture<span class="token punctuation">.</span><span class="token constant">TRILINEAR_SAMPLINGMODE</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> texture<span class="token operator">:</span> Texture<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="cubetextureassettask" tabindex="-1"><a class="header-anchor" href="#cubetextureassettask" aria-hidden="true">#</a> CubeTextureAssetTask</h3>
<p>与 TextureAssetTask 相同，但用于立方体纹理。</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> extensions<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> noMipmap<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">boolean</span><span class="token punctuation">,</span> files<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> texture<span class="token operator">:</span> CubeTexture<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="hdrcubetextureassettask" tabindex="-1"><a class="header-anchor" href="#hdrcubetextureassettask" aria-hidden="true">#</a> HDRCubeTextureAssetTask</h3>
<p>与 CubeTextureAssetTask 相同，但用于 HDR 立方体纹理</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> size<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">,</span> noMipmap <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span> generateHarmonics <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">,</span> useInGammaSpace <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span> usePMREMGenerator <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> texture<span class="token operator">:</span> HDRCubeTexture<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="equirectangularcubetextureassettask" tabindex="-1"><a class="header-anchor" href="#equirectangularcubetextureassettask" aria-hidden="true">#</a> EquiRectangularCubeTextureAssetTask</h3>
<p>与 CubeTextureAssetTask 相同，但用于 Equirectangular 立方体纹理</p>
<p>构造函数签名：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token function">constructor</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> url<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> size<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">,</span> noMipmap <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span> useInGammaSpace <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>额外属性：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">public</span> texture<span class="token operator">:</span> EquiRectangularCubeTexture<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="使用加载界面" tabindex="-1"><a class="header-anchor" href="#使用加载界面" aria-hidden="true">#</a> 使用加载界面</h2>
<p>默认情况下，AssetsManager 会在加载资产时显示加载界面：</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Ffeatures%2Fscene%2Floader.jpg&amp;w=1080&amp;q=75" alt="loading screen"></p>
<p>如果你想禁用加载界面，必须把 <code v-pre>useDefaultLoadingScreen</code> 设置为 <code v-pre>false</code> 。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>assetsManager<span class="token punctuation">.</span>useDefaultLoadingScreen <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在使用 <code v-pre>SceneLoader</code> 加载场景时，如果 <code v-pre>ShowLoadingScreen</code> 设置为 <code v-pre>true</code>（默认），则也会显示加载界面。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span>ShowLoadingScreen <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>同样，你也可以使用以下方法手动显示或隐藏加载界面：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>engine<span class="token punctuation">.</span><span class="token function">displayLoadingUI</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
engine<span class="token punctuation">.</span><span class="token function">hideLoadingUI</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>加载界面的文字使用 <code v-pre>loadingUIText</code> 控制：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>engine<span class="token punctuation">.</span>loadingUIText <span class="token operator">=</span> <span class="token string">"text"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>背景颜色使用 <code v-pre>loadingUIBackgroundColor </code> 控制：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>engine<span class="token punctuation">.</span>loadingUIBackgroundColor <span class="token operator">=</span> <span class="token string">"red"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="笔记" tabindex="-1"><a class="header-anchor" href="#笔记" aria-hidden="true">#</a> 笔记</h2>
<p>使用ES6树摇功能导入 AssetsManager 或 SceneLoader 时，需要导入对应的加载器：</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token string">"@babylonjs/core/Loading/Plugins/babylonFileLoader"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> AssetsManager <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@babylonjs/core/Misc/assetsManager"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><a href="https://github.com/BabylonJS/Babylon.js/issues/5760" target="_blank" rel="noopener noreferrer">https://github.com/BabylonJS/Babylon.js/issues/5760<ExternalLinkIcon/></a></li>
<li><a href="https://doc.babylonjs.com/divingDeeper/developWithBjs/treeShaking#loaders" target="_blank" rel="noopener noreferrer">https://doc.babylonjs.com/divingDeeper/developWithBjs/treeShaking#loaders<ExternalLinkIcon/></a></li>
</ul>
</template>
