<template><h1 id="加载任意文件类型" tabindex="-1"><a class="header-anchor" href="#加载任意文件类型" aria-hidden="true">#</a> 加载任意文件类型</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#使用sceneloader">使用SceneLoader</RouterLink><ul><li><RouterLink to="#基础用法">基础用法</RouterLink></li></ul></li><li><RouterLink to="#sceneloader-append">SceneLoader.Append</RouterLink></li><li><RouterLink to="#sceneloader-load">SceneLoader.Load</RouterLink></li><li><RouterLink to="#sceneloader-importmesh">SceneLoader.ImportMesh</RouterLink></li><li><RouterLink to="#sceneloader-loadassetcontainer">SceneLoader.LoadAssetContainer</RouterLink></li><li><RouterLink to="#sceneloader-importanimations">SceneLoader.ImportAnimations</RouterLink></li><li><RouterLink to="#sceneloader-appendasync">SceneLoader.AppendAsync</RouterLink></li><li><RouterLink to="#高级用法">高级用法</RouterLink></li><li><RouterLink to="#加载多个资产">加载多个资产</RouterLink></li><li><RouterLink to="#直接加载base64编码模型">直接加载base64编码模型</RouterLink></li></ul></nav>
<h2 id="使用sceneloader" tabindex="-1"><a class="header-anchor" href="#使用sceneloader" aria-hidden="true">#</a> 使用SceneLoader</h2>
<h3 id="基础用法" tabindex="-1"><a class="header-anchor" href="#基础用法" aria-hidden="true">#</a> 基础用法</h3>
<p>要加载指定类型的文件，Babylon 必须首先引用该文件类型的插件。</p>
<p>目前可以找到的插件有：</p>
<ul>
<li>.glTF也用于二进制版本的.glb</li>
<li>.obj</li>
<li>.stl</li>
</ul>
<p>要快速添加对<strong>所有加载器</strong>的支持，可以在网页中添加以下脚本：</p>
<p>生产版本：</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://cdn.babylonjs.com/babylon.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>预览版本（测试版本）：</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://preview.babylonjs.com/babylon.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://preview.babylonjs.com/loaders/babylonjs.loaders.min.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>有关 NPM 的用法，请参阅：<a href="https://www.npmjs.com/package/babylonjs-loaders" target="_blank" rel="noopener noreferrer">https://www.npmjs.com/package/babylonjs-loaders<ExternalLinkIcon/></a></p>
<p>一旦引用了该插件，就可以使用<code v-pre>SceneLoader</code>类，它提供了一些加载方法。</p>
<h2 id="sceneloader-append" tabindex="-1"><a class="header-anchor" href="#sceneloader-append" aria-hidden="true">#</a> SceneLoader.Append</h2>
<p>从文件中加载所有的Babylon资产，并将它们附加到场景中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">Append</span><span class="token punctuation">(</span><span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"duck.gltf"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// do something with the scene</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#WGZLGJ" target="_blank" rel="noopener noreferrer">附加模型示例<ExternalLinkIcon/></a></p>
<p>只要二进制数据经过base64编码，也可以从数据字符串中加载一个.glb二进制文件</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> base64_model_content <span class="token operator">=</span> <span class="token string">"data:;base64,BASE 64 ENCODED DATA..."</span><span class="token punctuation">;</span>
<span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">Append</span><span class="token punctuation">(</span><span class="token string">""</span><span class="token punctuation">,</span> base64_model_content<span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> 
    <span class="token comment">// do something with the scene</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>请注意，字符串数据中允许有两种mime类型</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> base64_model_content <span class="token operator">=</span> <span class="token string">"data:application/octet-stream;base64,-BASE 64 ENCODED DATA-"</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> base64_model_content <span class="token operator">=</span> <span class="token string">"data:model/gltf-binary;base64,-BASE 64 ENCODED DATA-"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#7F6S08#55" target="_blank" rel="noopener noreferrer">从二进制字符串中加载.glb示例<ExternalLinkIcon/></a></p>
<h2 id="sceneloader-load" tabindex="-1"><a class="header-anchor" href="#sceneloader-load" aria-hidden="true">#</a> SceneLoader.Load</h2>
<p>从文件中加载所有的Babylon资产并创建一个新场景</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">Load</span><span class="token punctuation">(</span><span class="token string">"/assets/"</span><span class="token punctuation">,</span> <span class="token string">"batman.obj"</span><span class="token punctuation">,</span> engine<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> 
   <span class="token comment">// do something with the scene</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sceneloader-importmesh" tabindex="-1"><a class="header-anchor" href="#sceneloader-importmesh" aria-hidden="true">#</a> SceneLoader.ImportMesh</h2>
<p>从文件中导入网格，并将它们添加到场景中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// The first parameter can be set to null to load all meshes and skeletons</span>
<span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">ImportMesh</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"myMesh1"</span><span class="token punctuation">,</span> <span class="token string">"myMesh2"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"duck.gltf"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">meshes<span class="token punctuation">,</span> particleSystems<span class="token punctuation">,</span> skeletons</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// do something with the meshes and skeletons</span>
    <span class="token comment">// particleSystems are always null for glTF assets</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#JUKXQD" target="_blank" rel="noopener noreferrer">导入网格示例<ExternalLinkIcon/></a></p>
<h2 id="sceneloader-loadassetcontainer" tabindex="-1"><a class="header-anchor" href="#sceneloader-loadassetcontainer" aria-hidden="true">#</a> SceneLoader.LoadAssetContainer</h2>
<p>从文件中加载所有的Babylon资产，但不将它们追加到场景中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">LoadAssetContainer</span><span class="token punctuation">(</span><span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"duck.gltf"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">container</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> meshes <span class="token operator">=</span> container<span class="token punctuation">.</span>meshes<span class="token punctuation">;</span>
    <span class="token keyword">var</span> materials <span class="token operator">=</span> container<span class="token punctuation">.</span>materials<span class="token punctuation">;</span>
    <span class="token comment">//...</span>

    <span class="token comment">// Adds all elements to the scene</span>
    container<span class="token punctuation">.</span><span class="token function">addAllToScene</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sceneloader-importanimations" tabindex="-1"><a class="header-anchor" href="#sceneloader-importanimations" aria-hidden="true">#</a> SceneLoader.ImportAnimations</h2>
<p>从文件中加载动画并将它们合并到场景中，可以使用选项和回调来定制导入过程</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">ImportAnimations</span><span class="token punctuation">(</span><span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"Elf_run.gltf"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#UGD0Q0#62" target="_blank" rel="noopener noreferrer">导入动画示例<ExternalLinkIcon/></a></p>
<h2 id="sceneloader-appendasync" tabindex="-1"><a class="header-anchor" href="#sceneloader-appendasync" aria-hidden="true">#</a> SceneLoader.AppendAsync</h2>
<p>这些函数也有返回promise的异步版本</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">AppendAsync</span><span class="token punctuation">(</span><span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"duck.gltf"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// do something with the scene</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="高级用法" tabindex="-1"><a class="header-anchor" href="#高级用法" aria-hidden="true">#</a> 高级用法</h2>
<p>使用<code v-pre>onPluginActivatedObservable</code>来设置属性和调用特定加载器的方法</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span>OnPluginActivatedObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">loader</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>loader<span class="token punctuation">.</span>name <span class="token operator">===</span> <span class="token string">"gltf"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// do something with the loader</span>
        <span class="token comment">// loader.&lt;option1> = &lt;...></span>
        <span class="token comment">// loader.&lt;option2> = &lt;...></span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>或者，静态的同步<code v-pre>SceneLoader</code>函数会返回插件</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> loader <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">Load</span><span class="token punctuation">(</span><span class="token string">"./"</span><span class="token punctuation">,</span> <span class="token string">"duck.gltf"</span><span class="token punctuation">,</span> engine<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// do something with the scene</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// do something with the loader</span>
<span class="token comment">// loader.&lt;option1> = &lt;...></span>
<span class="token comment">// loader.&lt;option2> = &lt;...></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="加载多个资产" tabindex="-1"><a class="header-anchor" href="#加载多个资产" aria-hidden="true">#</a> 加载多个资产</h2>
<p>为了帮助加载多个资产，可以使用AssetsManager类。参见<RouterLink to="/babylonjs/divingDeeper/importers/assetManager.html">资产管理器</RouterLink>。</p>
<h2 id="直接加载base64编码模型" tabindex="-1"><a class="header-anchor" href="#直接加载base64编码模型" aria-hidden="true">#</a> 直接加载base64编码模型</h2>
<p>Babylon.JS支持直接从base64编码的数据URL加载模型，而不需要创建一个对象URL或下载文件。当从base64数据URL加载时，插件不会被自动检测（一些glb格式除外）。当使用base64数据url时，pluginExtension参数应该被设置，以确保正确的插件被用于加载模型。</p>
<p>最小 base64 编码模型文件的格式为：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token literal-property property">data</span><span class="token operator">:</span><span class="token punctuation">;</span>base64<span class="token punctuation">,</span><span class="token operator">&lt;</span>base64_encoded_file_contents<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>base64前的;和它后面的,都是必须的。请看这里，有一个以base64编码加载obj文件的<a href="https://playground.babylonjs.com/#58T0JY" target="_blank" rel="noopener noreferrer">例子<ExternalLinkIcon/></a>。</p>
</template>
