<template><h1 id="绘制边界盒-bounding-boxes" tabindex="-1"><a class="header-anchor" href="#绘制边界盒-bounding-boxes" aria-hidden="true">#</a> 绘制边界盒 Bounding Boxes</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>在Babylon中绘制网格周围的边界盒是非常容易的。你可以把边界盒想象成一个可见的盒子，让你的物体完全置于其中。它涵盖了物体的外部 &quot;边界&quot;。</p>
<p>让我们先在一个单一物体周围绘制一个边界盒。你可以从默认的playground开始。</p>
<p>假设场景中有一个球体，其名字为 &quot;sphere&quot;。</p>
<p>要在球体周围绘制边界盒，你需要做的就是将<code v-pre>showBoundingBox</code>属性设置为<code v-pre>true</code>。</p>
<p>代码如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span>showBoundingBox <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>很简单吧？</p>
<p><a href="https://playground.babylonjs.com/#4F33I3" target="_blank" rel="noopener noreferrer">边界盒示例<ExternalLinkIcon/></a></p>
<p>好吧，让我们把它变得更复杂一点。假设场景中还有一个地面，名字为 &quot;ground&quot;，你想在包括球体和地面的区域周围绘制一个边界盒。</p>
<p>要做到这一点，我们要得到两个网格边界信息的最小值和最大值，并用特殊的方法来比较两个 vector3 的值，得到最小值和最大值。然后我们将球体的边界信息设置为这个新的最小和最大值。让我们来试试。</p>
<p>让我们首先声明4个新的变量，这些变量将保存球体和地面的最小和最大边界信息。像这样。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> sphereMin <span class="token operator">=</span> sphere<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimum<span class="token punctuation">;</span>
<span class="token keyword">let</span> sphereMax <span class="token operator">=</span> sphere<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximum<span class="token punctuation">;</span>

<span class="token keyword">let</span> groundMin <span class="token operator">=</span> ground<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimum<span class="token punctuation">;</span>
<span class="token keyword">let</span> groundMax <span class="token operator">=</span> ground<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximum<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>好的，现在让我们声明两个新的变量，并使用上面提到的那些特殊方法来比较两个网格的最小和最大边界信息。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> newMin <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Minimize</span><span class="token punctuation">(</span>sphereMin<span class="token punctuation">,</span> groundMin<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">let</span> newMax <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Maximize</span><span class="token punctuation">(</span>sphereMax<span class="token punctuation">,</span> groundMax<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>所以，现在newMin和newMax是两个物体的最小和最大的边界！这就是我们要做的。所以接下来我们将根据newMin和newMax将球体的边界信息设置为一组新的边界数据</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span><span class="token function">setBoundingInfo</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>BoundingInfo</span><span class="token punctuation">(</span>newMin<span class="token punctuation">,</span> newMax<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>最后，就像以前一样，我们然后显示球体的边界盒。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span>showBoundingBox <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4F33I3#1" target="_blank" rel="noopener noreferrer">多物体边界盒示例<ExternalLinkIcon/></a></p>
<p>我们上面使用的技术有一个问题。我们实际上改变了球体的边界信息，使其成为包括球体和地面的新边界信息。实际上有一个更好的方法，那就是不考虑球体的边界信息，而是在方法中引入父级功能。</p>
<p>首先，让我们创建一个新的通用网格，像这样。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> parent <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Mesh</span><span class="token punctuation">(</span><span class="token string">"parent"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>现在让我们使用这个通用网格作为球体和地面的父级；</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span><span class="token function">setParent</span><span class="token punctuation">(</span>parent<span class="token punctuation">)</span><span class="token punctuation">;</span>
ground<span class="token punctuation">.</span><span class="token function">setParent</span><span class="token punctuation">(</span>parent<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>最后，我们不要设置边界信息和显示球体的边界盒，而是将其改为父级。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>parent<span class="token punctuation">.</span><span class="token function">setBoundingInfo</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>BoundingInfo</span><span class="token punctuation">(</span>newMin<span class="token punctuation">,</span> newMax<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    
parent<span class="token punctuation">.</span>showBoundingBox <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4F33I3#2" target="_blank" rel="noopener noreferrer">多物体边界盒更好的实现方式示例<ExternalLinkIcon/></a></p>
<p>发现问题了吗？边界盒不再与物体的边界一致了，是吗？这是有原因的。这是因为到目前为止，我们使用的是局部坐标，而不是世界坐标。所以从技术上讲，我们看到的边界盒是正确的尺寸，但它是围绕父网格绘制的......在这种情况下，它的轴心点在原点。当你注释掉这一行时，你可以清楚地看到问题所在。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4F33I3#3" target="_blank" rel="noopener noreferrer">多物体边界盒更好的实现方式示例<ExternalLinkIcon/></a></p>
<p>如果你想获得物体的世界边界其实是很容易做到的。我们将对sphereMin, sphereMax, groundMin, groundMax的值做一些小的修改，像这样</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> sphereMin <span class="token operator">=</span> sphere<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimumWorld<span class="token punctuation">;</span>
<span class="token keyword">let</span> sphereMax <span class="token operator">=</span> sphere<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximumWorld<span class="token punctuation">;</span>

<span class="token keyword">let</span> groundMin <span class="token operator">=</span> ground<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimumWorld<span class="token punctuation">;</span>
<span class="token keyword">let</span> groundMax <span class="token operator">=</span> ground<span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximumWorld<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4F33I3#4" target="_blank" rel="noopener noreferrer">世界坐标的边界盒示例<ExternalLinkIcon/></a></p>
<p>那么，如果你有一堆物体，想得到所有物体的边界盒，会发生什么？你不会想为每一个物体手动操作吧？因此，我们将在混合中引入一个循环!</p>
<p>像前面一样，我们将确保有一个父网格，并且想要包含在边界盒中的每个物体都将被父网格所包含。</p>
<p>这里有趣的技术是，我们可以通过一个数组来循环浏览父网格的每一个 &quot;子网格&quot;。让我们先声明一个新的变量，它将是父网格的所有子网格的一个数组。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> childMeshes <span class="token operator">=</span> parent<span class="token punctuation">.</span><span class="token function">getChildMeshes</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>接下来，声明两个新的变量，用来保存最小和最大的边界值。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> min <span class="token operator">=</span> childMeshes<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimumWorld<span class="token punctuation">;</span>
<span class="token keyword">let</span> max <span class="token operator">=</span> childMeshes<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximumWorld<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>我们将这些最小和最大变量的起始值设置为第一个子网格的世界最小和世界最大边界信息。</p>
<p>现在我们可以循环浏览所有的子网格，并根据每个子网格的新边界信息不断地更新最小和最大值。它看起来像这样。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">let</span> i<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">;</span> i<span class="token operator">&lt;</span>childMeshes<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">let</span> meshMin <span class="token operator">=</span> childMeshes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>minimumWorld<span class="token punctuation">;</span>
    <span class="token keyword">let</span> meshMax <span class="token operator">=</span> childMeshes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getBoundingInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>boundingBox<span class="token punctuation">.</span>maximumWorld<span class="token punctuation">;</span>

    min <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Minimize</span><span class="token punctuation">(</span>min<span class="token punctuation">,</span> meshMin<span class="token punctuation">)</span><span class="token punctuation">;</span>
    max <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Maximize</span><span class="token punctuation">(</span>max<span class="token punctuation">,</span> meshMax<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4F33I3#6" target="_blank" rel="noopener noreferrer">遍历网格绘制边界盒示例<ExternalLinkIcon/></a></p>
<p>要更深入研究边界盒，请查看 <a href="https://doc.babylonjs.com/typedoc/classes/babylon.boundingbox" target="_blank" rel="noopener noreferrer">API<ExternalLinkIcon/></a></p>
</template>
