<template><h1 id="网格高亮-highlightlayer" tabindex="-1"><a class="header-anchor" href="#网格高亮-highlightlayer" aria-hidden="true">#</a> 网格高亮 HighlightLayer</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#如何使网格高亮">如何使网格高亮</RouterLink></li><li><RouterLink to="#如何使用">如何使用？</RouterLink><ul><li><RouterLink to="#默认用例">默认用例</RouterLink></li><li><RouterLink to="#停止高亮显示">停止高亮显示</RouterLink></li><li><RouterLink to="#自发光输入">自发光输入</RouterLink></li></ul></li><li><RouterLink to="#深入">深入</RouterLink><ul><li><RouterLink to="#重叠高亮">重叠高亮</RouterLink></li><li><RouterLink to="#模糊度">模糊度</RouterLink></li><li><RouterLink to="#内部辉光和外部辉光">内部辉光和外部辉光</RouterLink></li><li><RouterLink to="#排除网格">排除网格</RouterLink></li><li><RouterLink to="#多个相机">多个相机</RouterLink></li><li><RouterLink to="#渲染组-rendering-groups">渲染组 Rendering Groups</RouterLink></li></ul></li><li><RouterLink to="#选项">选项</RouterLink></li></ul></nav>
<h2 id="如何使网格高亮" tabindex="-1"><a class="header-anchor" href="#如何使网格高亮" aria-hidden="true">#</a> 如何使网格高亮</h2>
<p>我们经常需要让场景中的网格高亮显示。这个功能听起来很容易，但实际还要处理边缘、模糊和抗锯齿这些问题。</p>
<p>这个教程就是解决如何让网格高亮显示的。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fhighlight-mesh%2Fintroduction.png&amp;w=1920&amp;q=75" alt=""></p>
<h2 id="如何使用" tabindex="-1"><a class="header-anchor" href="#如何使用" aria-hidden="true">#</a> 如何使用？</h2>
<p>首先，必须确保创建的引擎开启了模板 stencil 。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> engine <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Engine</span><span class="token punctuation">(</span>canvas<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">stencil</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>HighlightLayer 依靠模板 stencil 来确定它需要绘制图片的哪个部分。</p>
<h3 id="默认用例" tabindex="-1"><a class="header-anchor" href="#默认用例" aria-hidden="true">#</a> 默认用例</h3>
<p>对于基础模型，我们只需要在场景中实例化一个高亮层 HighlightLayer，并在其中添加想要高亮显示的网格。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Green</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>高亮颜色由 addMesh 方法的第2个参数驱动：<a href="https://playground.babylonjs.com/#1KUJ0A#305" target="_blank" rel="noopener noreferrer">示例<ExternalLinkIcon/></a>。</p>
<h3 id="停止高亮显示" tabindex="-1"><a class="header-anchor" href="#停止高亮显示" aria-hidden="true">#</a> 停止高亮显示</h3>
<p>如果一个高亮的网格不再需要高亮，我们可以简单地把它从图层中删除。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Green</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
hl<span class="token punctuation">.</span><span class="token function">removeMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#102" target="_blank" rel="noopener noreferrer">停止高亮示例<ExternalLinkIcon/></a></p>
<h3 id="自发光输入" tabindex="-1"><a class="header-anchor" href="#自发光输入" aria-hidden="true">#</a> 自发光输入</h3>
<p>如果我们愿意，我们也可以使用自发光纹理 emissive texture 作为高亮颜色的来源。只需在添加网格方法的第3个参数中传入true即可。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>hl1<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Black</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#57" target="_blank" rel="noopener noreferrer">自发光输入示例<ExternalLinkIcon/></a></p>
<p>我们可以注意到，球体的一边是黄色的，而另一边是灰色的。颜色是不均匀的。</p>
<h2 id="深入" tabindex="-1"><a class="header-anchor" href="#深入" aria-hidden="true">#</a> 深入</h2>
<h3 id="重叠高亮" tabindex="-1"><a class="header-anchor" href="#重叠高亮" aria-hidden="true">#</a> 重叠高亮</h3>
<p>目前示例中两个网格重叠的部分没有高亮显示，我们的第1个需求是，让重叠部分高亮显示。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Green</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
hl<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>ground<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Red</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#1" target="_blank" rel="noopener noreferrer">重叠部分没有高亮<ExternalLinkIcon/></a></p>
<p>这是针对性能优化的默认行为。如果我们在性能好的机器上运行，可以创建多个高亮层 HighlightLayer 解决这个问题：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl1<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">White</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> hl2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl2"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl2<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>ground<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Red</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#2" target="_blank" rel="noopener noreferrer">重叠高亮示例<ExternalLinkIcon/></a></p>
<h3 id="模糊度" tabindex="-1"><a class="header-anchor" href="#模糊度" aria-hidden="true">#</a> 模糊度</h3>
<p>我们的第2个需求是，能够对高亮部分的模糊度进行动画处理。我们可以在运行时通过图层的模糊度属性动态地改变它。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl2"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl2<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>ground<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Red</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> alpha <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span><span class="token function">registerBeforeRender</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  alpha <span class="token operator">+=</span> <span class="token number">0.06</span><span class="token punctuation">;</span>

  hl2<span class="token punctuation">.</span>blurHorizontalSize <span class="token operator">=</span> <span class="token number">0.3</span> <span class="token operator">+</span> Math<span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span>alpha<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">0.6</span> <span class="token operator">+</span> <span class="token number">0.6</span><span class="token punctuation">;</span>
  hl2<span class="token punctuation">.</span>blurVerticalSize <span class="token operator">=</span> <span class="token number">0.3</span> <span class="token operator">+</span> Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>alpha <span class="token operator">/</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">0.6</span> <span class="token operator">+</span> <span class="token number">0.6</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#4" target="_blank" rel="noopener noreferrer">高亮模糊度动画示例<ExternalLinkIcon/></a></p>
<h3 id="内部辉光和外部辉光" tabindex="-1"><a class="header-anchor" href="#内部辉光和外部辉光" aria-hidden="true">#</a> 内部辉光和外部辉光</h3>
<p>最后，我们可以很容易地启用/禁用高光层的内部和外部辉光。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Add the highlight layer.</span>
<span class="token keyword">var</span> hl1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl1<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">White</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
hl1<span class="token punctuation">.</span>outerGlow <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> hl2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl2"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
hl2<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>ground<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Red</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
hl2<span class="token punctuation">.</span>innerGlow <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#1KUJ0A#3" target="_blank" rel="noopener noreferrer">内部辉光和外部辉光示例<ExternalLinkIcon/></a></p>
<p>可以注意到示例中，白色只在球体内部发光，红色只在平面外发光。</p>
<h3 id="排除网格" tabindex="-1"><a class="header-anchor" href="#排除网格" aria-hidden="true">#</a> 排除网格</h3>
<p>在我们的场景中，透明网格可能无法与其他高亮的网格一起正确渲染。<a href="https://playground.babylonjs.com/#2FFOYQ#6" target="_blank" rel="noopener noreferrer">渲染错误示例<ExternalLinkIcon/></a></p>
<p>在这种情况下，尝试将它们从高亮生成过程中排除，以解决这个问题。<a href="https://playground.babylonjs.com/#2FFOYQ#7" target="_blank" rel="noopener noreferrer">排除网格示例<ExternalLinkIcon/></a></p>
<h3 id="多个相机" tabindex="-1"><a class="header-anchor" href="#多个相机" aria-hidden="true">#</a> 多个相机</h3>
<p>默认情况下，高亮层将应用于所有激活的相机，但它会在相机上产生额外的处理，这是没有必要的。</p>
<p>解决方法是，我们可以很容易地在选项中指定我们的高亮与什么相机有关。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> hl1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">camera</span><span class="token operator">:</span> camera <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
hl1<span class="token punctuation">.</span><span class="token function">addMesh</span><span class="token punctuation">(</span>sphere<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Green</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#CDHKK#7" target="_blank" rel="noopener noreferrer">多相机示例<ExternalLinkIcon/></a></p>
<h3 id="渲染组-rendering-groups" tabindex="-1"><a class="header-anchor" href="#渲染组-rendering-groups" aria-hidden="true">#</a> 渲染组 Rendering Groups</h3>
<p>如果我们在应用程序中依赖渲染组，请注意高亮部分需要我们的场景的模板 stencil 和深度信息 depth info 才能正确工作。</p>
<p>所以我们可以用以下命令禁止渲染组之间的清除：<code v-pre>scene.setRenderingAutoClearDepthStencil(1, false, false)</code>，其中第1个参数是渲染组id，第2个参数是防止组间自动清除深度，最后一个参数是防止组间自动清除模板信息。</p>
<h2 id="选项" tabindex="-1"><a class="header-anchor" href="#选项" aria-hidden="true">#</a> 选项</h2>
<p>选项对象的可用成员有：</p>
<ul>
<li>mainTextureRatio? : number - 应用于画布尺寸的乘法系数，以计算用于生成高亮物体的渲染目标 render target 尺寸（越小越快）。</li>
<li>mainTextureFixedSize?: number - 强制执行固定尺寸的纹理，以确保不受尺寸调整影响的模糊。</li>
<li>blurTextureSizeRatio? : number - 在模糊的第一步中应用于主纹理尺寸的乘法系数，以减少要模糊的图片的尺寸（越小越快）。</li>
<li>blurVerticalSize?: number - 模糊纹理的垂直模糊度大小。</li>
<li>blurHorizontalSize?: number - 模糊纹理的水平模糊度大小。</li>
<li>alphaBlendingMode? : number - 用于应用模糊的Alpha混合模式。默认为 combine。</li>
<li>camera? Camera - 连接到该层的相机（只有这个相机可以看到高亮）。</li>
</ul>
<p>我们可以在构建高亮层的过程中传递它们：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> hl1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HighlightLayer</span><span class="token punctuation">(</span><span class="token string">"hl1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">camera</span><span class="token operator">:</span> myCamera <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://doc.babylonjs.com/typedoc/classes/babylon.highlightlayer" target="_blank" rel="noopener noreferrer">HighlightLayer API<ExternalLinkIcon/></a></p>
</template>
