<template><h1 id="合并网格-mergemeshes" tabindex="-1"><a class="header-anchor" href="#合并网格-mergemeshes" aria-hidden="true">#</a> 合并网格 MergeMeshes</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#原生-babylon-js-函数">原生 Babylon.js 函数</RouterLink></li><li><RouterLink to="#使用你自己的合并函数">使用你自己的合并函数</RouterLink></li><li><RouterLink to="#将网格与构造实体几何合并">将网格与构造实体几何合并</RouterLink></li></ul></nav>
<h2 id="原生-babylon-js-函数" tabindex="-1"><a class="header-anchor" href="#原生-babylon-js-函数" aria-hidden="true">#</a> 原生 Babylon.js 函数</h2>
<p>使用<code v-pre>Mesh</code>类的<code v-pre>MergeMeshes</code>静态方法，可以很容易地将一些网格合并为一个单一的网格。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> newMesh <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">MergeMeshes</span><span class="token punctuation">(</span>arrayOfMeshes<span class="token punctuation">,</span> disposeSource<span class="token punctuation">,</span> allow32BitsIndices<span class="token punctuation">,</span> meshSubclass<span class="token punctuation">,</span> subdivideWithSubMeshes<span class="token punctuation">,</span> multiMultiMaterials<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><table>
<thead>
<tr>
<th style="text-align:left">参数</th>
<th style="text-align:left">描述</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">arrayOfMeshes</td>
<td style="text-align:left">一个Meshes的数组。它们应该都是相同的材质。</td>
</tr>
<tr>
<td style="text-align:left">disposeSource (可选)</td>
<td style="text-align:left">当为true时（默认），源网格将在完成后被处理掉。</td>
</tr>
<tr>
<td style="text-align:left">allow32BitsIndices (可选)</td>
<td style="text-align:left">当顶点的总和 &gt; 64k 时，必须将其设置为 true。</td>
</tr>
<tr>
<td style="text-align:left">meshSubclass (可选)</td>
<td style="text-align:left">如设置，顶点插入到这个Mesh中。然后网格可以被合并到一个Mesh子类中。</td>
</tr>
<tr>
<td style="text-align:left">subdivideWithSubMeshes (可选)</td>
<td style="text-align:left">当为 true（默认为 false）时，将网格细分为具有网格源的 subMesh 数组。</td>
</tr>
<tr>
<td style="text-align:left">multiMultiMaterials (可选)</td>
<td style="text-align:left">当为true（默认为false）时，对网格进行细分并接受多个多维材质，忽略<code v-pre>subdivideWithSubMeshes</code>。</td>
</tr>
</tbody>
</table>
<p>由于<code v-pre>multiMultiMaterials</code>默认为false，合并后的网格将只有一个材质（取自第一个网格）。</p>
<p><a href="https://playground.babylonjs.com/#INZ0Z0#5" target="_blank" rel="noopener noreferrer">合并网格示例<ExternalLinkIcon/></a></p>
<p>有关使用合并网格的更多详细信息，请参阅<a href="https://doc.babylonjs.com/divingDeeper/materials/using/multiMaterials" target="_blank" rel="noopener noreferrer">此页面<ExternalLinkIcon/></a>。</p>
<h2 id="使用你自己的合并函数" tabindex="-1"><a class="header-anchor" href="#使用你自己的合并函数" aria-hidden="true">#</a> 使用你自己的合并函数</h2>
<p>如果你想用一个自已实现的函数将网格合并成一个新的网格，你可以使用下面的代码作为基础，并根据你的需要进行改进。</p>
<p>注意：小心，当你合并克隆的网格时，你需要在调用该函数前用<code v-pre>computeWorldMatrix</code>更新网格的世界矩阵。</p>
<p>注意：本文涵盖了内部合并的过程。你也可以使用<code v-pre>BABYLON.VertexData</code>对象和它的<code v-pre>merge()</code>函数来获得更简单的解决方案。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> <span class="token function-variable function">mergeMeshes</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">meshName<span class="token punctuation">,</span> arrayObj<span class="token punctuation">,</span> scene</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">var</span> arrayPos <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayNormal <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayUv <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayUv2 <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayColor <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayMatricesIndices <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayMatricesWeights <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> arrayIndice <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> savedPosition <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> savedNormal <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> newMesh <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Mesh</span><span class="token punctuation">(</span>meshName<span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> UVKind <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> UV2Kind <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> ColorKind <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> MatricesIndicesKind <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> MatricesWeightsKind <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>

  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">!=</span> arrayObj<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">isVerticesDataPresent</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UVKind<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> UVKind <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">isVerticesDataPresent</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UV2Kind<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> UV2Kind <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">isVerticesDataPresent</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>ColorKind<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> ColorKind <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">isVerticesDataPresent</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesIndicesKind<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> MatricesIndicesKind <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">isVerticesDataPresent</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesWeightsKind<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> MatricesWeightsKind <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">!=</span> arrayObj<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> ite <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    <span class="token keyword">var</span> iter <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    arrayPos<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>PositionKind<span class="token punctuation">)</span><span class="token punctuation">;</span>
    arrayNormal<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>NormalKind<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>UVKind<span class="token punctuation">)</span> arrayUv <span class="token operator">=</span> arrayUv<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UVKind<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>UV2Kind<span class="token punctuation">)</span> arrayUv2 <span class="token operator">=</span> arrayUv2<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UV2Kind<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>ColorKind<span class="token punctuation">)</span> arrayColor <span class="token operator">=</span> arrayColor<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>ColorKind<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>MatricesIndicesKind<span class="token punctuation">)</span> arrayMatricesIndices <span class="token operator">=</span> arrayMatricesIndices<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesIndicesKind<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>MatricesWeightsKind<span class="token punctuation">)</span> arrayMatricesWeights <span class="token operator">=</span> arrayMatricesWeights<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesWeightsKind<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">var</span> maxValue <span class="token operator">=</span> savedPosition<span class="token punctuation">.</span>length <span class="token operator">/</span> <span class="token number">3</span><span class="token punctuation">;</span>

    arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">computeWorldMatrix</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">var</span> worldMatrix <span class="token operator">=</span> arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getWorldMatrix</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> ite <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> ite <span class="token operator">!=</span> arrayPos<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>length<span class="token punctuation">;</span> ite <span class="token operator">+=</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">var</span> vertex <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">TransformCoordinates</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span>arrayPos<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>ite<span class="token punctuation">]</span><span class="token punctuation">,</span> arrayPos<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>ite <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> arrayPos<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>ite <span class="token operator">+</span> <span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> worldMatrix<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedPosition<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>x<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedPosition<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedPosition<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>z<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> iter <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> iter <span class="token operator">!=</span> arrayNormal<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>length<span class="token punctuation">;</span> iter <span class="token operator">+=</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">var</span> vertex <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">TransformNormal</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span>arrayNormal<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>iter<span class="token punctuation">]</span><span class="token punctuation">,</span> arrayNormal<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>iter <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> arrayNormal<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>iter <span class="token operator">+</span> <span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> worldMatrix<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedNormal<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>x<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedNormal<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      savedNormal<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>vertex<span class="token punctuation">.</span>z<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> tmp <span class="token operator">=</span> arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">getIndices</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>it <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> it <span class="token operator">!=</span> tmp<span class="token punctuation">.</span>length<span class="token punctuation">;</span> it<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      arrayIndice<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>tmp<span class="token punctuation">[</span>it<span class="token punctuation">]</span> <span class="token operator">+</span> maxValue<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    arrayIndice <span class="token operator">=</span> arrayIndice<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span>tmp<span class="token punctuation">)</span><span class="token punctuation">;</span>

    arrayObj<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>PositionKind<span class="token punctuation">,</span> savedPosition<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>NormalKind<span class="token punctuation">,</span> savedNormal<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>arrayUv<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UVKind<span class="token punctuation">,</span> arrayUv<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>arrayUv2<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>UV2Kind<span class="token punctuation">,</span> arrayUv<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>arrayColor<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>ColorKind<span class="token punctuation">,</span> arrayUv<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>arrayMatricesIndices<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesIndicesKind<span class="token punctuation">,</span> arrayUv<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>arrayMatricesWeights<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> newMesh<span class="token punctuation">.</span><span class="token function">setVerticesData</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VertexBuffer<span class="token punctuation">.</span>MatricesWeightsKind<span class="token punctuation">,</span> arrayUv<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  newMesh<span class="token punctuation">.</span><span class="token function">setIndices</span><span class="token punctuation">(</span>arrayIndice<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> newMesh<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="将网格与构造实体几何合并" tabindex="-1"><a class="header-anchor" href="#将网格与构造实体几何合并" aria-hidden="true">#</a> 将网格与构造实体几何合并</h2>
<p>你也可以通过使用CSG类的减法、逆法、联合法和交叉法来构造复杂的网格。</p>
<p>例如，假设你想创建一个有内径和外径的 &quot;管道 &quot;形状（也就是说，不只是一个 &quot;管子&quot;网格，那是一个没有 &quot;厚度 &quot;的弯曲平面）。这可以通过首先创建一个 &quot;圆柱体 &quot;网格，然后从它的内部减去一个 &quot;管子 &quot;网格来构建。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">createPipe</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">diamInner</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">diamOuter</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">length</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">scene</span><span class="token operator">:</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Scene</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh <span class="token punctuation">{</span>
  <span class="token comment">// Create the outer wall using a Cylinder mesh</span>
  <span class="token keyword">const</span> mOuter <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateCylinder</span><span class="token punctuation">(</span>
    <span class="token string">"mOuter"</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span>
      <span class="token literal-property property">diameter</span><span class="token operator">:</span> diamOuter<span class="token punctuation">,</span>
      <span class="token literal-property property">height</span><span class="token operator">:</span> length<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    scene<span class="token punctuation">,</span>
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Create the inner wall using a Tube mesh</span>
  <span class="token keyword">const</span> mInner <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateTube</span><span class="token punctuation">(</span>
    <span class="token string">"mInner"</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span>
      <span class="token literal-property property">path</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span>length <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> length <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token literal-property property">radius</span><span class="token operator">:</span> diamInner <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span>
      <span class="token literal-property property">sideOrientation</span><span class="token operator">:</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token constant">DOUBLESIDE</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    scene<span class="token punctuation">,</span>
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Create CSG objects from each mesh</span>
  <span class="token keyword">const</span> outerCSG <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span><span class="token constant">CSG</span><span class="token punctuation">.</span><span class="token function">FromMesh</span><span class="token punctuation">(</span>mOuter<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> innerCSG <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span><span class="token constant">CSG</span><span class="token punctuation">.</span><span class="token function">FromMesh</span><span class="token punctuation">(</span>mInner<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Create a new CSG object by subtracting the inner tube from the outer cylinder</span>
  <span class="token keyword">const</span> pipeCSG <span class="token operator">=</span> outerCSG<span class="token punctuation">.</span><span class="token function">subtract</span><span class="token punctuation">(</span>innerCSG<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Create the resulting mesh from the new CSG object</span>
  <span class="token keyword">const</span> mPipe <span class="token operator">=</span> pipeCSG<span class="token punctuation">.</span><span class="token function">toMesh</span><span class="token punctuation">(</span><span class="token string">"mPipe"</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Dispose of the meshes, no longer needed</span>
  mInner<span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  mOuter<span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  scene<span class="token punctuation">.</span><span class="token function">removeMesh</span><span class="token punctuation">(</span>mInner<span class="token punctuation">)</span><span class="token punctuation">;</span>
  scene<span class="token punctuation">.</span><span class="token function">removeMesh</span><span class="token punctuation">(</span>mOuter<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// Return the result</span>
  <span class="token keyword">return</span> mPipe<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#L5T0DK" target="_blank" rel="noopener noreferrer">CSG流程示例<ExternalLinkIcon/></a></p>
</template>
