<template><h1 id="创建场景和模型" tabindex="-1"><a class="header-anchor" href="#创建场景和模型" aria-hidden="true">#</a> 创建场景和模型</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#创建场景和模型-1">创建场景和模型</RouterLink></li><li><RouterLink to="#打个招呼">打个招呼</RouterLink></li></ul></nav>
<h2 id="创建场景和模型-1" tabindex="-1"><a class="header-anchor" href="#创建场景和模型-1" aria-hidden="true">#</a> 创建场景和模型</h2>
<p>无论是创建整个世界还是只是将一个模型放入网页中，都需要一个包含世界或模型的场景、一个用于查看它的相机、一盏灯来照亮它，当然，至少需要一个可视对象作为模型。所有模型，无论是一个盒子还是一个复杂的角色，都是由三角形或面的网格制成的。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fwireframe.png&amp;w=1920&amp;q=75" alt=""></p>
<p>可以使用代码直接在Babylon.js中创建大量网格，或者，从使用其他软件导入。这里，我们从一个盒子开始。</p>
<p>这些页面上的示例可以在 <a href="https://playground.cnbabylon.com/#2HTFJ7" target="_blank" rel="noopener noreferrer">Playground<ExternalLinkIcon/></a> 中查看，这是在网页上试用Babylon.js的地方。</p>
<h2 id="打个招呼" tabindex="-1"><a class="header-anchor" href="#打个招呼" aria-hidden="true">#</a> 打个招呼</h2>
<p>所有使用Babylon.js引擎的项目都需要一个添加了相机和灯光的场景。然后才可以创建盒子。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> scene <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Scene</span><span class="token punctuation">(</span>engine<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> camera <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ArcRotateCamera</span><span class="token punctuation">(</span><span class="token string">"camera"</span><span class="token punctuation">,</span> <span class="token operator">-</span>Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2.5</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
camera<span class="token punctuation">.</span><span class="token function">attachControl</span><span class="token punctuation">(</span>canvas<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> light <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HemisphericLight</span><span class="token punctuation">(</span><span class="token string">"light"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> box <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateBox</span><span class="token punctuation">(</span><span class="token string">"box"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>像大多数使用 MeshBuilder 创建的网格一样，创建的盒子以其中心为原点，需要三个参数。它们是名称name（字符串）、选项options（JavaScript 对象）、和场景scene。如果选项为空对象 {}，盒子的宽度、高度和深度默认为1个单位大小。</p>
<p>为了能在playground上使用，需要将它们放在一个名为 <strong>createScene</strong> 的函数中，该函数必须返回一个场景。playground应用程序负责其余的工作。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token function-variable function">createScene</span> <span class="token operator">=</span>  <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> scene <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Scene</span><span class="token punctuation">(</span>engine<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> camera <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ArcRotateCamera</span><span class="token punctuation">(</span><span class="token string">"camera"</span><span class="token punctuation">,</span> <span class="token operator">-</span>Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2.5</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    camera<span class="token punctuation">.</span><span class="token function">attachControl</span><span class="token punctuation">(</span>canvas<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> light <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HemisphericLight</span><span class="token punctuation">(</span><span class="token string">"light"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> box <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateBox</span><span class="token punctuation">(</span><span class="token string">"box"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">return</span> scene<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>由于此时只有一个场景scene，该参数可以从相机、灯光和盒子中删除，因为它们默认放置在当前场景中。</p>
<p><a href="https://playground.cnbabylon.com/#2HTFJ7" target="_blank" rel="noopener noreferrer">https://playground.cnbabylon.com/#2HTFJ7<ExternalLinkIcon/></a></p>
<p>创建了盒子后，我们可以通过检查器<strong>Inspector</strong>按钮来保存或导出playground中的场景</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fpgpartmenu.png&amp;w=1920&amp;q=75" alt=""></p>
<p>在右侧的属性面板上切换到工具选项卡，选择要导出的类型，<em>.babylon</em> 格式或 <em>GLB</em> 格式。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fexport.png&amp;w=1920&amp;q=75" alt=""></p>
<p>现在我们有了一个文件，可以用它来演示如何在网页中查看。</p>
</template>
