<template><h1 id="在网页上浏览模型" tabindex="-1"><a class="header-anchor" href="#在网页上浏览模型" aria-hidden="true">#</a> 在网页上浏览模型</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#在网页上浏览模型-1">在网页上浏览模型</RouterLink></li></ul></nav>
<h2 id="在网页上浏览模型-1" tabindex="-1"><a class="header-anchor" href="#在网页上浏览模型-1" aria-hidden="true">#</a> 在网页上浏览模型</h2>
<p>如果模型是一种Babylon.js能识别的文件类型，可以借助<a href="https://doc.babylonjs.com/extensions/babylonViewer" target="_blank" rel="noopener noreferrer">Babylon.js查看器<ExternalLinkIcon/></a>使用 <code v-pre>&lt;babylon&gt;</code> 元素在网页上显示场景或模型。支持的文件类型包括： <strong>.babylon</strong>、<strong>.gltf</strong> 和 <strong>glb</strong>，建议使用 <strong>.glb</strong>。无论场景是使用 Babylon.js构建的还是使用你偏好的3D软件创建的，都没有区别。 <code v-pre>&lt;babylon&gt;</code> 元素会自动调整尺寸以适应容器大小。</p>
<p>为了使用查看器，需要将如下代码添加到 HTML 页面的 <code v-pre>&lt;script&gt;</code> 元素中</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://cdn.babylonjs.com/viewer/babylon.viewer.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>添加后，将 <code v-pre>&lt;babylon&gt;</code> 元素放到适当的容器中，并指定<em>model</em>属性为文件路径。</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>babylon</span> <span class="token attr-name">model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>模型路径<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>babylon</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><RouterLink to="/babylonjs/start/chap1/viewer-example.html">示例</RouterLink></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fview1.png&amp;w=1920&amp;q=75" alt=""></p>
<p>想要将模型用于网页上的游戏或应用，你首先需要知道如何导入它们。</p>
</template>
