<template><h1 id="动态纹理-dynamic-textures" tabindex="-1"><a class="header-anchor" href="#动态纹理-dynamic-textures" aria-hidden="true">#</a> 动态纹理 Dynamic Textures</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#创建和应用">创建和应用</RouterLink></li><li><RouterLink to="#写入文本">写入文本</RouterLink></li><li><RouterLink to="#画布方法">画布方法</RouterLink><ul><li><RouterLink to="#绘制曲线">绘制曲线</RouterLink></li><li><RouterLink to="#图片">图片</RouterLink></li></ul></li><li><RouterLink to="#示例">示例</RouterLink></li><li><RouterLink to="#文本和区域匹配">文本和区域匹配</RouterLink><ul><li><RouterLink to="#文本适配区域">文本适配区域</RouterLink></li><li><RouterLink to="#区域适配文本">区域适配文本</RouterLink></li></ul></li><li><RouterLink to="#序列化">序列化</RouterLink></li></ul></nav>
<p>动态纹理的工作原理是创建一个画布，你可以使用<a href="https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API" target="_blank" rel="noopener noreferrer">HTML5画布<ExternalLinkIcon/></a>的所有方法在上面绘画。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fdyntext.png&amp;w=1920&amp;q=75" alt=""></p>
<h2 id="创建和应用" tabindex="-1"><a class="header-anchor" href="#创建和应用" aria-hidden="true">#</a> 创建和应用</h2>
<p>可以使用只有三个参数的<code v-pre>dynamicTexture</code>函数简单实现。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> myDynamicTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>DynamicTexture</span><span class="token punctuation">(</span>name<span class="token punctuation">,</span> option<span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><code v-pre>minmaps</code>， <code v-pre>sampling mode</code> 和 <code v-pre>texture</code>的默认值可以被通过赋值被覆盖。</p>
<p><code v-pre>name</code>和<code v-pre>scene</code>参数是显而易见的，而<code v-pre>option</code>参数则决定了动态纹理的宽度和高度，它可以是三个值之一。</p>
<ul>
<li>一个已经创建的画布，在这种情况下，会使用canvas.width和canvas.height。</li>
<li>一个具有宽度和高度属性的对象。</li>
<li>一个数字，在这种情况下，宽度和高度都被设置为这个数字。</li>
</ul>
<p>一旦创建了动态纹理，就可以按照通常的方式将其作为材质的漫反射纹理使用。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> myMaterial <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"Mat"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>                    
myMaterial<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> myDynamicTexture<span class="token punctuation">;</span>
mesh<span class="token punctuation">.</span>material <span class="token operator">=</span> myMaterial<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="写入文本" tabindex="-1"><a class="header-anchor" href="#写入文本" aria-hidden="true">#</a> 写入文本</h2>
<p>可以使用<code v-pre>drawText</code>方法，直接将文本写在动态纹理上。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>myDynamicTexture<span class="token punctuation">.</span><span class="token function">drawText</span><span class="token punctuation">(</span>text<span class="token punctuation">,</span> x<span class="token punctuation">,</span> y<span class="token punctuation">,</span> font<span class="token punctuation">,</span> color<span class="token punctuation">,</span> canvas color<span class="token punctuation">,</span> invertY<span class="token punctuation">,</span> update<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>参数如下：</p>
<ul>
<li>text：字符串，要写的字。</li>
<li>x：数字，与左手边的距离。</li>
<li>y：数字，与顶部或底部边缘的距离，取决于invertY。</li>
<li>font：字符串，字体定义，形式为font-style、font-size、font_name。</li>
<li>invertY：布尔值，默认为true，在这种情况下，y是离顶部的距离，当为假时，y是离底部的距离，字母反转。</li>
<li>update：布尔值，默认为true，动态纹理将立即被更新。</li>
</ul>
<p><a href="https://playground.babylonjs.com/#5ZCGRM#2" target="_blank" rel="noopener noreferrer">绘制文本示例<ExternalLinkIcon/></a></p>
<h2 id="画布方法" tabindex="-1"><a class="header-anchor" href="#画布方法" aria-hidden="true">#</a> 画布方法</h2>
<p>通过以下方式获得画布上下文：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> ctx <span class="token operator">=</span> myDynamicTexture<span class="token punctuation">.</span><span class="token function">getContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>暴露了HTML5画布元素的所有能力。</p>
<h3 id="绘制曲线" tabindex="-1"><a class="header-anchor" href="#绘制曲线" aria-hidden="true">#</a> 绘制曲线</h3>
<p>作为示例，使用二次曲线绘图：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>ctx<span class="token punctuation">.</span><span class="token function">beginPath</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span><span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">62.5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">60</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token number">65</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">62.5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">quadraticCurveTo</span><span class="token punctuation">(</span><span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ctx<span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>要应用绘图，动态纹理需要更新</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>myDynamicTexture<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>注意：如果你不想使用<code v-pre>invertY</code>，请使用<code v-pre>update(false)</code>。</p>
<p><a href="https://playground.babylonjs.com/#5ZCGRM#3" target="_blank" rel="noopener noreferrer">绘制曲线示例<ExternalLinkIcon/></a></p>
<h3 id="图片" tabindex="-1"><a class="header-anchor" href="#图片" aria-hidden="true">#</a> 图片</h3>
<p>可以使用 <code v-pre>drawImage</code> 方法添加图片来填充部分或整个画布。请记住，在将图片指定给画布之前，必须等待图片的加载，并在之后更新动态纹理。</p>
<p>对于整个图片</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> img <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
img<span class="token punctuation">.</span>src <span class="token operator">=</span> <span class="token string">'PATH TO IMAGE'</span><span class="token punctuation">;</span>
img<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    ctx<span class="token punctuation">.</span><span class="token function">drawImage</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    myDynamicTexture<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>用于部分图片缩放到画布的一部分</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> img <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
img<span class="token punctuation">.</span>src <span class="token operator">=</span> <span class="token string">'PATH TO IMAGE'</span><span class="token punctuation">;</span>
img<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

ctx<span class="token punctuation">.</span><span class="token function">drawImage</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> image start x<span class="token punctuation">,</span> image start y<span class="token punctuation">,</span> image width<span class="token punctuation">,</span> image height<span class="token punctuation">,</span> canvas to x<span class="token punctuation">,</span> canvas to y<span class="token punctuation">,</span> destination width<span class="token punctuation">,</span> destination height<span class="token punctuation">)</span><span class="token punctuation">;</span>
myDynamicTexture<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#5ZCGRM#4" target="_blank" rel="noopener noreferrer">增加图片<ExternalLinkIcon/></a></p>
<h2 id="示例" tabindex="-1"><a class="header-anchor" href="#示例" aria-hidden="true">#</a> 示例</h2>
<p><a href="https://playground.babylonjs.com/#5ZCGRM#1" target="_blank" rel="noopener noreferrer">示例<ExternalLinkIcon/></a></p>
<h2 id="文本和区域匹配" tabindex="-1"><a class="header-anchor" href="#文本和区域匹配" aria-hidden="true">#</a> 文本和区域匹配</h2>
<p><strong>对于单行文本</strong>，可以将文本装入指定的区域，或将一个区域装入指定的文本。</p>
<h3 id="文本适配区域" tabindex="-1"><a class="header-anchor" href="#文本适配区域" aria-hidden="true">#</a> 文本适配区域</h3>
<p>你有一个有宽度和高度的平面，<code v-pre>planeWidth</code>和<code v-pre>planeHeight</code>，为了形成动态纹理的宽度和高度，将平面的宽度和高度都乘以相同的数字，以保持长宽比。乘以的数字定义了文本的清晰度，小的数字会产生模糊的文本。现在你可以创建动态纹理了。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> DTWidth <span class="token operator">=</span> planeWidth <span class="token operator">*</span> <span class="token number">60</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> DTHeight <span class="token operator">=</span> planeHeight <span class="token operator">*</span> <span class="token number">60</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> dynamicTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>DynamicTexture</span><span class="token punctuation">(</span><span class="token string">"DynamicTexture"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span>DTWidth<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span>DTHeight<span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>接下来，使用任何大小的字体书写并测量动态纹理上的文本宽度。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> ctx <span class="token operator">=</span> dynamicTexture<span class="token punctuation">.</span><span class="token function">getContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> size <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">;</span> <span class="token comment">//any value will work</span>
ctx<span class="token punctuation">.</span>font <span class="token operator">=</span> size <span class="token operator">+</span> <span class="token string">"px "</span> <span class="token operator">+</span> font_type<span class="token punctuation">;</span>
<span class="token keyword">var</span> textWidth <span class="token operator">=</span> ctx<span class="token punctuation">.</span><span class="token function">measureText</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">.</span>width<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>文字宽度与应用的字体大小的比例可以应用于动态纹理宽度，以确定适合该平面的字体大小。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> ratio <span class="token operator">=</span> textWidth<span class="token operator">/</span>size<span class="token punctuation">;</span>

<span class="token keyword">var</span> font_size <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>DTWidth <span class="token operator">/</span> ratio<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果你愿意，你可以对比例应用一个乘数，乘数越大，文本越小，边距越大。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> font_size <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>DTWidth <span class="token operator">/</span> <span class="token punctuation">(</span>ratio <span class="token operator">*</span> <span class="token number">1.1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>现在设置字体并绘制文本</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> font <span class="token operator">=</span> font_size <span class="token operator">+</span> <span class="token string">"px "</span> <span class="token operator">+</span> font_type<span class="token punctuation">;</span>
dynamicTexture<span class="token punctuation">.</span><span class="token function">drawText</span><span class="token punctuation">(</span>text<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> font<span class="token punctuation">,</span> <span class="token string">"#000000"</span><span class="token punctuation">,</span> <span class="token string">"#ffffff"</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>最后设置并应用平面的材质。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> mat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"mat"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
mat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> dynamicTexture<span class="token punctuation">;</span>
plane<span class="token punctuation">.</span>material <span class="token operator">=</span> mat<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#TMHF80#1" target="_blank" rel="noopener noreferrer">单行文本适配区域示例<ExternalLinkIcon/></a></p>
<h3 id="区域适配文本" tabindex="-1"><a class="header-anchor" href="#区域适配文本" aria-hidden="true">#</a> 区域适配文本</h3>
<p>取一个固定高度的平面网格，planeHeight和设定字体大小的文字，然后你可以计算平面必须有多宽才能容纳文字。为了做到这一点，你需要知道文字在动态纹理上所占的宽度。这是用一个临时的动态纹理和测量文本来计算的。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> temp <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>DynamicTexture</span><span class="token punctuation">(</span><span class="token string">"DynamicTexture"</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> tmpctx <span class="token operator">=</span> temp<span class="token punctuation">.</span><span class="token function">getContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
tmpctx<span class="token punctuation">.</span>font <span class="token operator">=</span> font<span class="token punctuation">;</span>
<span class="token keyword">var</span> DTWidth <span class="token operator">=</span> tmpctx<span class="token punctuation">.</span><span class="token function">measureText</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">.</span>width<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为动态纹理选择一个高度，DTHeight，并保持平面与动态纹理的长宽比。</p>
<ol>
<li>计算比例 ratio planeHeight:DTHeight;</li>
<li>使用这个比例来计算平面的宽度Width = DTWidth * ratio;</li>
<li>创建动态纹理，作为材质使用，宽度和高度分别为DTWidth和DTHeight。</li>
<li>在动态纹理上绘制文字。</li>
<li>创建具有宽度和高度的平面 planeWidth 和 planeHeight。</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> planeHeight <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> DTHeight <span class="token operator">=</span> <span class="token number">256</span><span class="token punctuation">;</span> <span class="token comment">//or set as wished</span>
<span class="token keyword">var</span> ratio <span class="token operator">=</span> planeHeight<span class="token operator">/</span>DTHeight<span class="token punctuation">;</span>
<span class="token keyword">var</span> planeWidth <span class="token operator">=</span> DTWidth <span class="token operator">*</span> ratio<span class="token punctuation">;</span>

<span class="token keyword">var</span> dynamicTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>DynamicTexture</span><span class="token punctuation">(</span><span class="token string">"DynamicTexture"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span>DTWidth<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span>DTHeight<span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> mat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"mat"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
mat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> dynamicTexture<span class="token punctuation">;</span>
dynamicTexture<span class="token punctuation">.</span><span class="token function">drawText</span><span class="token punctuation">(</span>text<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> font<span class="token punctuation">,</span> <span class="token string">"#000000"</span><span class="token punctuation">,</span> <span class="token string">"#ffffff"</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//use of null, null centers the text</span>
    
<span class="token keyword">var</span> plane <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreatePlane</span><span class="token punctuation">(</span><span class="token string">"plane"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span>planeWidth<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span>planeHeight<span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
plane<span class="token punctuation">.</span>material <span class="token operator">=</span> mat<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#TMHF80" target="_blank" rel="noopener noreferrer">区域适配文本示例<ExternalLinkIcon/></a></p>
<h2 id="序列化" tabindex="-1"><a class="header-anchor" href="#序列化" aria-hidden="true">#</a> 序列化</h2>
<p>动态纹理可以使用<code v-pre>SceneSerializer.Serialize()</code>与场景一起序列化，或者使用<code v-pre>SceneSerializer.SerializeMesh()</code>序列化一个网格。</p>
<p>注意：请确保在序列化之前，场景已经准备好了。</p>
<p>这个<a href="https://playground.babylonjs.com/#FU0ES5" target="_blank" rel="noopener noreferrer">示例<ExternalLinkIcon/></a>演示了序列化一个与网格上的材质相关的动态纹理。</p>
</template>
