<template><h1 id="双面材质" tabindex="-1"><a class="header-anchor" href="#双面材质" aria-hidden="true">#</a> 双面材质</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#frontuvs-和-backuvs">FrontUVs 和 BackUVs</RouterLink></li><li><RouterLink to="#双面示例">双面示例</RouterLink></li></ul></nav>
<p>平面网格都有正面和背面，比如平面plane、圆盘disc或多边形polygon。所有这些网格都有两个面，只有当选项<code v-pre>sideOrientation</code>被设置为<code v-pre>BABYLON.Mesh.DOUBLESIDE</code>时，才能看到这两个面。</p>
<p>然而，很多网格都有<code v-pre>sideOrientation</code>选项，这个方法也适用于它们。在这种情况下，可以把前面当成外面，后面当成里面。</p>
<p>要有前后不同的纹理，前面和后面的图片必须在同一个文件中，就像下面这个文件一样</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fdifferent-material-front-back%2Fcard.jpg&amp;w=1920&amp;q=75" alt=""></p>
<p>然后使用<code v-pre>frontUVs</code>和<code v-pre>backUVs</code>选项将其分割。</p>
<h2 id="frontuvs-和-backuvs" tabindex="-1"><a class="header-anchor" href="#frontuvs-和-backuvs" aria-hidden="true">#</a> FrontUVs 和 BackUVs</h2>
<p><code v-pre>frontUVs</code>和<code v-pre>backUVs</code>的形式都是<code v-pre>Vector4(u0, v0, u1, v1)</code>，其中0&lt;= u0, v0, u1, v1 &lt;= 1，(u0, v0)是图像剪切矩形的左下方坐标，(u1, v1)是右上方坐标。</p>
<p>为了分割上面的图片，可以使用两个变量</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> f <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector4</span><span class="token punctuation">(</span><span class="token number">0.5</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// front image = half the whole image along the width </span>
<span class="token keyword">var</span> b <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector4</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.5</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// back image = second half along the width</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>然后放入选项中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> plane <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreatePlane</span><span class="token punctuation">(</span><span class="token string">"plane"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">height</span><span class="token operator">:</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">0.665</span><span class="token punctuation">,</span> <span class="token literal-property property">sideOrientation</span><span class="token operator">:</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token constant">DOUBLESIDE</span><span class="token punctuation">,</span> <span class="token literal-property property">frontUVs</span><span class="token operator">:</span> f<span class="token punctuation">,</span> <span class="token literal-property property">backUVs</span><span class="token operator">:</span> b<span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>要考虑到图片部分的宽度和高度比例。</p>
<p>然后只需创建一个<code v-pre>StandardMaterial</code>并将纹理设置到图片上即可。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> mat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">""</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
mat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"URL to Image File"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
plane<span class="token punctuation">.</span>material <span class="token operator">=</span> mat<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="双面示例" tabindex="-1"><a class="header-anchor" href="#双面示例" aria-hidden="true">#</a> 双面示例</h2>
<p><a href="https://playground.babylonjs.com/#LXZPJK#3" target="_blank" rel="noopener noreferrer">扑克牌示例<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#4G18GY#2" target="_blank" rel="noopener noreferrer">多边形示例<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#165IV6#74" target="_blank" rel="noopener noreferrer">圆柱示例<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#K6M44R#3" target="_blank" rel="noopener noreferrer">球体外部示例<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#K6M44R#4" target="_blank" rel="noopener noreferrer">球体内部示例<ExternalLinkIcon/></a></p>
</template>
