<template><h1 id="多维材质-multimaterial" tabindex="-1"><a class="header-anchor" href="#多维材质-multimaterial" aria-hidden="true">#</a> 多维材质 MultiMaterial</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#合并的网格">合并的网格</RouterLink></li></ul></nav>
<p>多维材质是用来将不同的材质应用于同一物体的不同部分，如下图：</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FMaterials%2Fmulti.png&amp;w=1920&amp;q=75" alt=""></p>
<p>为了能够定义一个多维材质，首先要定义多个标准材质。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> material0 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"mat0"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
material0<span class="token punctuation">.</span>diffuseColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
material0<span class="token punctuation">.</span>bumpTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"normalMap.jpg"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token operator">&lt;</span>br<span class="token operator">/</span><span class="token operator">></span>
    
<span class="token keyword">var</span> material1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"mat1"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
material1<span class="token punctuation">.</span>diffuseColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  
<span class="token keyword">var</span> material2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"mat2"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
material2<span class="token punctuation">.</span>emissiveColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0.4</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.4</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后创建一个多维材质<code v-pre>MultiMaterial</code>，以便将它们全部收集起来。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> multimat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>MultiMaterial</span><span class="token punctuation">(</span><span class="token string">"multi"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
multimat<span class="token punctuation">.</span>subMaterials<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>material0<span class="token punctuation">)</span><span class="token punctuation">;</span>
multimat<span class="token punctuation">.</span>subMaterials<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>material1<span class="token punctuation">)</span><span class="token punctuation">;</span>
multimat<span class="token punctuation">.</span>subMaterials<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>material2<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>现在可以将多维材质应用到网格上。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> sphere <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">CreateSphere</span><span class="token punctuation">(</span><span class="token string">"Sphere0"</span><span class="token punctuation">,</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
sphere<span class="token punctuation">.</span>material <span class="token operator">=</span> multimat<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>但如果这样做，你会看到球体只会使用第一个子材质（红色凸起的那个）。这是因为在默认情况下，一个网格被设计为只使用一种材质。</p>
<p>你可以通过使用<code v-pre>subMeshes</code>属性来指定网格的哪一部分使用特定的材质。默认情况下，每个网格都只有一个子网格。</p>
<p>要定义多个子网格，你只需要使用如下代码：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>sphere<span class="token punctuation">.</span>subMeshes <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> verticesCount <span class="token operator">=</span> sphere<span class="token punctuation">.</span><span class="token function">getTotalVertices</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SubMesh</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> verticesCount<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">900</span><span class="token punctuation">,</span> sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SubMesh</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> verticesCount<span class="token punctuation">,</span> <span class="token number">900</span><span class="token punctuation">,</span> <span class="token number">900</span><span class="token punctuation">,</span> sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SubMesh</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> verticesCount<span class="token punctuation">,</span> <span class="token number">1800</span><span class="token punctuation">,</span> <span class="token number">2088</span><span class="token punctuation">,</span> sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在这种情况下，你将有3部分:</p>
<ul>
<li>一个从索引0开始到索引900</li>
<li>一个从索引900开始到索引1800</li>
<li>一个从索引1800开始到索引3880</li>
</ul>
<p>一个子网格是这样定义的:</p>
<ul>
<li>要使用的材质的索引（该索引用于在多维材质的<code v-pre>subMaterials</code>集合中找到正确的材质）。</li>
<li>第一个顶点的索引和使用的顶点数量（例如，为了优化碰撞）。</li>
<li>第一个要使用的顶点的索引和顶点数量</li>
<li>父网格</li>
</ul>
<p>所以通过上面的代码，你可以在球体的顶部使用第一个材质，在中间部分使用第二个材质，在球体的底部使用最后一个材质。</p>
<p><a href="https://playground.babylonjs.com/#2Q4S2S#268" target="_blank" rel="noopener noreferrer">使用多维材质的球体示例<ExternalLinkIcon/></a></p>
<h2 id="合并的网格" tabindex="-1"><a class="header-anchor" href="#合并的网格" aria-hidden="true">#</a> 合并的网格</h2>
<p>当把网格合并到一起时，将最后的参数<code v-pre>multiMultiMaterial</code>设置为<code v-pre>true</code>，<code v-pre>subMeshes</code>数组会自动创建所有合并网格的子网格。每个子网格的材质也会包含在合并后的网格的新多维材质中。这个功能忽略了参数（subdivideWithSubMeshes）。</p>
<p><a href="https://playground.babylonjs.com/#INZ0Z0#59" target="_blank" rel="noopener noreferrer">合并网格示例<ExternalLinkIcon/></a></p>
<p>当把网格合并在一起，并把倒数第二个参数（subdivideWithSubMeshes）设置为true，但把最后一个参数（multiMultiMaterial）设为false时，subMeshes阵列会自动创建，每个合并的网格都是新网格的一个子网格。你必须将正确的 subMesh 索引分配给正确的材质索引。</p>
<p>当你通过合并网格形成mergedMesh，阵列的顺序是[Mesh1, mesh2]，而multiMaterials的subMaterials阵列包含的材料顺序是[mat1, mat2]，那么为了让Mesh2的子网格拥有材料mat2，你需要设置</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mergedMesh<span class="token punctuation">.</span>subMeshes<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">.</span>materialIndex <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#INZ0Z0#6" target="_blank" rel="noopener noreferrer">合并网格示例<ExternalLinkIcon/></a></p>
</template>
