<template><h1 id="反射和折射" tabindex="-1"><a class="header-anchor" href="#反射和折射" aria-hidden="true">#</a> 反射和折射</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#关于环境贴图-environment-mapping">关于环境贴图 environment mapping</RouterLink></li><li><RouterLink to="#静态环境贴图-cubetexture-和类似">静态环境贴图（CubeTexture 和类似）</RouterLink><ul><li><RouterLink to="#天空盒立方体贴图-skybox-cubemaps">天空盒立方体贴图 Skybox cubemaps</RouterLink></li><li><RouterLink to="#本地立方体贴图-local-cubemaps">本地立方体贴图 Local cubemaps</RouterLink></li><li><RouterLink to="#矩形立方体纹理-equirectangularcubetexture">矩形立方体纹理 EquiRectangularCubeTexture</RouterLink></li><li><RouterLink to="#hdrcubetexture">HDRCubeTexture</RouterLink></li><li><RouterLink to="#作为环境贴图的扁平纹理">作为环境贴图的扁平纹理</RouterLink></li></ul></li></ul></nav>
<h2 id="关于环境贴图-environment-mapping" tabindex="-1"><a class="header-anchor" href="#关于环境贴图-environment-mapping" aria-hidden="true">#</a> 关于环境贴图 environment mapping</h2>
<p>Babylon.js使用环境贴图 <em>environment mapping</em>（<a href="https://en.wikipedia.org/wiki/Reflection_mapping" target="_blank" rel="noopener noreferrer">维基百科<ExternalLinkIcon/></a>）来模拟反射（镜子材质）和折射（玻璃材质）。</p>
<p>环境贴图是世界的图片（从某个有利位置看到的），它被转换并应用于网格以模拟反射或折射。这些图片可以是单张图片或复合的全景图，可以是静态快照或动态更新以跟踪场景的变化。</p>
<p>一旦创建（如下所述），环境贴图可以在<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial" target="_blank" rel="noopener noreferrer">StandardMaterial<ExternalLinkIcon/></a>的<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial#reflectiontexture" target="_blank" rel="noopener noreferrer">.reflectionTexture<ExternalLinkIcon/></a>或<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial#reflectiontexture" target="_blank" rel="noopener noreferrer">.refractionTexture<ExternalLinkIcon/></a>中使用；环境贴图也可以在<a href="https://doc.babylonjs.com/divingDeeper/materials/using/introToPBR" target="_blank" rel="noopener noreferrer">Physically Based Rendering - PBR材质<ExternalLinkIcon/></a>中用于复杂的材质表面。</p>
<h2 id="静态环境贴图-cubetexture-和类似" tabindex="-1"><a class="header-anchor" href="#静态环境贴图-cubetexture-和类似" aria-hidden="true">#</a> 静态环境贴图（CubeTexture 和类似）</h2>
<p><a href="https://doc.babylonjs.com/typedoc/classes/babylon.cubetexture" target="_blank" rel="noopener noreferrer">CubeTexture<ExternalLinkIcon/></a>实例使用6张图片来制作一个静态的包围环境图（或 &quot;cubemap&quot;）。<a href="https://doc.babylonjs.com/typedoc/classes/babylon.cubetexture#constructor" target="_blank" rel="noopener noreferrer">CubeMap构造函数<ExternalLinkIcon/></a>接受一个基本的URL，并添加&quot;_px.jpg&quot;、&quot;_nx.jpg&quot;、&quot;_py.jpg&quot;、&quot;_ny.jpg&quot;、&quot;_pz.jpg &quot;和&quot;_nz.jpg &quot;来加载一个立方体的+x、-x、+y、-y、+z和-z面的图片。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FMaterials%2Fcubetexture1.png&amp;w=1920&amp;q=75" alt="CubeTexture"></p>
<p>（使用 <a href="https://doc.babylonjs.com/typedoc/classes/babylon.cubetexture#constructor" target="_blank" rel="noopener noreferrer">extensions 参数<ExternalLinkIcon/></a>自定义这些后缀，例如：用.png替换.jpg加载图片。）</p>
<p>尽管名称为“Texture”，但CubeTexture <strong>只能</strong>与 <a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial" target="_blank" rel="noopener noreferrer">StandardMaterial<ExternalLinkIcon/></a> 的<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial#reflectiontexture" target="_blank" rel="noopener noreferrer">.reflectionTexture<ExternalLinkIcon/></a> 或<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial#reflectiontexture" target="_blank" rel="noopener noreferrer">.refractionTexture<ExternalLinkIcon/></a> 属性一起使用，而不能与<a href="https://doc.babylonjs.com/typedoc/classes/babylon.standardmaterial#diffusetexture" target="_blank" rel="noopener noreferrer">.diffuseTexture<ExternalLinkIcon/></a> 等其他属性一起使用。</p>
<h3 id="天空盒立方体贴图-skybox-cubemaps" tabindex="-1"><a class="header-anchor" href="#天空盒立方体贴图-skybox-cubemaps" aria-hidden="true">#</a> 天空盒立方体贴图 Skybox cubemaps</h3>
<h3 id="本地立方体贴图-local-cubemaps" tabindex="-1"><a class="header-anchor" href="#本地立方体贴图-local-cubemaps" aria-hidden="true">#</a> 本地立方体贴图 Local cubemaps</h3>
<h3 id="矩形立方体纹理-equirectangularcubetexture" tabindex="-1"><a class="header-anchor" href="#矩形立方体纹理-equirectangularcubetexture" aria-hidden="true">#</a> 矩形立方体纹理 EquiRectangularCubeTexture</h3>
<h3 id="hdrcubetexture" tabindex="-1"><a class="header-anchor" href="#hdrcubetexture" aria-hidden="true">#</a> HDRCubeTexture</h3>
<h3 id="作为环境贴图的扁平纹理" tabindex="-1"><a class="header-anchor" href="#作为环境贴图的扁平纹理" aria-hidden="true">#</a> 作为环境贴图的扁平纹理</h3>
</template>
