<template><h1 id="视频纹理-videotexture" tabindex="-1"><a class="header-anchor" href="#视频纹理-videotexture" aria-hidden="true">#</a> 视频纹理 VideoTexture</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#从本地视频生成纹理">从本地视频生成纹理</RouterLink></li><li><RouterLink to="#从摄像头生成纹理">从摄像头生成纹理</RouterLink></li></ul></nav>
<h2 id="从本地视频生成纹理" tabindex="-1"><a class="header-anchor" href="#从本地视频生成纹理" aria-hidden="true">#</a> 从本地视频生成纹理</h2>
<p>如果你想在场景中显示一个视频，Babylon引擎有一个特殊的纹理可用。这种特殊纹理的工作方式与其他纹理类似，但有几个参数除外。这些参数包括视频URL（一个URL数组），视频纹理的大小（这里是256），场景，以及最后一个可选的布尔值，表示是否要使用<a href="https://en.wikipedia.org/wiki/Mipmap" target="_blank" rel="noopener noreferrer">mipmap<ExternalLinkIcon/></a>。</p>
<p>下面是我们Flat2009演示中的一个例子。</p>
<p><a href="https://playground.babylonjs.com/#ZMCFYA#83" target="_blank" rel="noopener noreferrer">视频纹理示例<ExternalLinkIcon/></a></p>
<p>这在演示的ZTV屏幕上播放视频（ecran=屏幕）。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>ecran<span class="token punctuation">.</span>material<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>VideoTexture</span><span class="token punctuation">(</span><span class="token string">"video"</span><span class="token punctuation">,</span> <span class="token string">"textures/babylonjs.mp4"</span><span class="token punctuation">,</span> scene<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://doc.babylonjs.com/typedoc/classes/babylon.videotexture" target="_blank" rel="noopener noreferrer">VideoTexture对象<ExternalLinkIcon/></a>接受一个视频数组（考虑到各种编解码器）。数组中第一个可以加载的视频......就是作为内容源的视频。目前，HTML5支持.mp4、.webm和.ogv视频格式。</p>
<p>内部的<a href="https://www.w3.org/wiki/HTML/Elements/video" target="_blank" rel="noopener noreferrer">视频DOM对象<ExternalLinkIcon/></a>可以通过<code v-pre>VideoTexture.video</code>属性访问......它允许你控制一些特性并监控视频的状态（如播放、暂停、循环、自动播放等）。请看上面的链接，了解完整的情况。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2FAdvanced%20Texturing%2F3.png&amp;w=1920&amp;q=75" alt=""></p>
<p>即使我们正在使用高级纹理技术，<code v-pre>VideoTexture</code>也是与<code v-pre>StandardMaterial</code>一起工作的。简单地说，它需要有光照。作为一个方便的替代方案或视频照明助手，你可能想在网格的基础材质上设置一个发光的颜色。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>ecran<span class="token punctuation">.</span>material<span class="token punctuation">.</span>emissiveColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><strong>移动设备不能自动播放视频</strong>。需要用户互动（如点击）来播放视频。在用户点击之前，视频纹理将是黑色的。播放视频的一个简单方法是这样的。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span><span class="token function-variable function">onPointerDown</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    videoTexture<span class="token punctuation">.</span>video<span class="token punctuation">.</span><span class="token function">play</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这将在场景中第一次点击时开始播放视频。</p>
<p><a href="https://playground.babylonjs.com/#CHQ4T#294" target="_blank" rel="noopener noreferrer">触发播放视频示例<ExternalLinkIcon/></a></p>
<p>如果你希望在加载期间显示一个纹理，可以在设置的<code v-pre>poster</code>属性中提供一个在加载期间或用户与视频互动之前显示的图像的URL。</p>
<p>还可以使用一个事件来检测你是否在浏览器中通过策略阻止自动播放：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>texture<span class="token punctuation">.</span>onUserActionRequestedObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    scene<span class="token punctuation">.</span><span class="token function-variable function">onPointerDown</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        videoTexture<span class="token punctuation">.</span>video<span class="token punctuation">.</span><span class="token function">play</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="从摄像头生成纹理" tabindex="-1"><a class="header-anchor" href="#从摄像头生成纹理" aria-hidden="true">#</a> 从摄像头生成纹理</h2>
<p>从v2.6开始，我们引入了对WebRTC的支持。所以现在你可以创建一个特定的 VideoTexture，它将连接到你的默认 WebCam。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>VideoTexture<span class="token punctuation">.</span><span class="token function">CreateFromWebCam</span><span class="token punctuation">(</span>scene<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">videoTexture</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">maxWidth</span><span class="token operator">:</span> <span class="token number">256</span><span class="token punctuation">,</span> <span class="token literal-property property">maxHeight</span><span class="token operator">:</span> <span class="token number">256</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>第三个参数是可选的，可用于定义 minWidth、maxWidth、minHeight 和 maxHeight。这些值将用于限制相机分辨率。</p>
</template>
