<template><h1 id="控制昼夜" tabindex="-1"><a class="header-anchor" href="#控制昼夜" aria-hidden="true">#</a> 控制昼夜</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>将图形用户界面GUI添加到场景的一种有用方法是 Babylon.js GUI。在虚拟现实中工作时，这个 GUI 是必要的，因为它被设计为位于 Babylon.js 场景画布内，而不是 HTML 文档的一部分。此 GUI 已预加载到 Playground 中，但它是一个额外的脚本，可加载到您自己的项目中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>script<span class="token operator">></span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>cdn<span class="token punctuation">.</span>babylonjs<span class="token punctuation">.</span>com<span class="token operator">/</span>gui<span class="token operator">/</span>babylon<span class="token punctuation">.</span>gui<span class="token punctuation">.</span>min<span class="token punctuation">.</span>js<span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>我们将使用一个包含两个元素的 GUI 面板：标题的文本块和通过设置灯光强度来改变昼夜的滑块。</p>
<p>首先需要创建一个特殊纹理，称为 <strong>AdvancedDynamicTexture</strong>，GUI 元素将在其上绘制。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> adt <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span><span class="token constant">GUI</span><span class="token punctuation">.</span>AdvancedDynamicTexture<span class="token punctuation">.</span><span class="token function">CreateFullscreenUI</span><span class="token punctuation">(</span><span class="token string">"UI"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>对于我们的世界，GUI 将是基于全屏的。</p>
<p>我们创建容器面板来保存屏幕右下角的其他元素。然后将其添加到高级动态纹理中。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> panel <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>GUI<span class="token punctuation">.</span>StackPanel</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span>width <span class="token operator">=</span> <span class="token string">"220px"</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span>top <span class="token operator">=</span> <span class="token string">"-50px"</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span>horizontalAlignment <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span><span class="token constant">GUI</span><span class="token punctuation">.</span>Control<span class="token punctuation">.</span><span class="token constant">HORIZONTAL_ALIGNMENT_RIGHT</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span>verticalAlignment <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span><span class="token constant">GUI</span><span class="token punctuation">.</span>Control<span class="token punctuation">.</span><span class="token constant">VERTICAL_ALIGNMENT_BOTTOM</span><span class="token punctuation">;</span>
adt<span class="token punctuation">.</span><span class="token function">addControl</span><span class="token punctuation">(</span>panel<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>接下来创建文本块并将其添加到面板上</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> header <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>GUI<span class="token punctuation">.</span>TextBlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
header<span class="token punctuation">.</span>text <span class="token operator">=</span> <span class="token string">"Night to Day"</span><span class="token punctuation">;</span>
header<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token string">"30px"</span><span class="token punctuation">;</span>
header<span class="token punctuation">.</span>color <span class="token operator">=</span> <span class="token string">"white"</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span><span class="token function">addControl</span><span class="token punctuation">(</span>header<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们创建并将滑块添加到面板上。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> slider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>GUI<span class="token punctuation">.</span>Slider</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>minimum <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>maximum <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>borderColor <span class="token operator">=</span> <span class="token string">"black"</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>color <span class="token operator">=</span> <span class="token string">"#AAAAAA"</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>background <span class="token operator">=</span> <span class="token string">"#white"</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>value <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token string">"20px"</span><span class="token punctuation">;</span>
slider<span class="token punctuation">.</span>width <span class="token operator">=</span> <span class="token string">"200px"</span><span class="token punctuation">;</span>
panel<span class="token punctuation">.</span><span class="token function">addControl</span><span class="token punctuation">(</span>slider<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们需要将可观察事件添加到滑块以改变光强度。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>slider<span class="token punctuation">.</span>onValueChangedObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">value</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>light<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        light<span class="token punctuation">.</span>intensity <span class="token operator">=</span> value<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KBS9I5#95" target="_blank" rel="noopener noreferrer">添加GUI的村庄<ExternalLinkIcon/></a></p>
</template>
