<template><h1 id="阴影" tabindex="-1"><a class="header-anchor" href="#阴影" aria-hidden="true">#</a> 阴影</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>到目前为止，我们已经使用的半球灯给出了环境光，但不适合产生阴影。我们可以使用聚光灯，但它们产生的阴影可能会比较微弱，所以我们将引入平行光。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span>  light <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>DirectionalLight</span><span class="token punctuation">(</span><span class="token string">"dir"</span><span class="token punctuation">,</span> direction<span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>像往常一样，方向是Vector3，场景参数是可选的。</p>
<p>设置其位置将影响任何创建的阴影的方向和长度。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>light<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>仅在 <strong>ShadowGenerator</strong> 对象创建时才会出现阴影，该对象是一个指定产生阴影的网格，并且将被投射阴影的网格被设置为接收阴影。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> shadowGenerator <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ShadowGenerator</span><span class="token punctuation">(</span><span class="token number">1024</span><span class="token punctuation">,</span> light<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>第一个参数是阴影贴图的大小和产生阴影的灯光。</p>
<p>我们还需要添加一个将产生阴影的网格。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>shadowGenerator<span class="token punctuation">.</span><span class="token function">addShadowCaster</span><span class="token punctuation">(</span>casting mesh<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>第2个可选参数，其默认值为<strong>false</strong>，允许网格的所有子物体投射阴影。</p>
<p>最后，我们也必须告诉被投射了阴影的网格接收阴影。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>receiving_mesh<span class="token punctuation">.</span>receiveShadows <span class="token operator">=</span> <span class="token boolean">true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在我们的案例中，我们需要在适当的位置</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> shadowGenerator <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ShadowGenerator</span><span class="token punctuation">(</span><span class="token number">1024</span><span class="token punctuation">,</span> light<span class="token punctuation">)</span><span class="token punctuation">;</span>

shadowGenerator<span class="token punctuation">.</span><span class="token function">addShadowCaster</span><span class="token punctuation">(</span>dude<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

ground<span class="token punctuation">.</span>receiveShadows <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#4G38H4#7" target="_blank" rel="noopener noreferrer">单独的阴影<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#96" target="_blank" rel="noopener noreferrer">整合阴影的村庄<ExternalLinkIcon/></a></p>
</template>
