<template><h1 id="创建汽车模型" tabindex="-1"><a class="header-anchor" href="#创建汽车模型" aria-hidden="true">#</a> 创建汽车模型</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#创建汽车模型-1">创建汽车模型</RouterLink></li></ul></nav>
<h2 id="创建汽车模型-1" tabindex="-1"><a class="header-anchor" href="#创建汽车模型-1" aria-hidden="true">#</a> 创建汽车模型</h2>
<p>这里创建汽车模型使用了MeshBuilder中的extrudePolygon方法，这个方法可以将在一个平面上的轮廓挤出，轮廓是一组按逆时针顺序排列的Vector3顶点，其中轮廓的曲线部分利用三角函数计算得出。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//base</span>
<span class="token keyword">const</span> outline <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">0.3</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0.2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>

<span class="token comment">//curved front</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> <span class="token number">20</span><span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    outline<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0.2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span>i <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">40</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>i <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">40</span><span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token comment">//top</span>
outline<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
outline<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">0.3</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> car <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">ExtrudePolygon</span><span class="token punctuation">(</span><span class="token string">"car"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">shape</span><span class="token operator">:</span> outline<span class="token punctuation">,</span> <span class="token literal-property property">depth</span><span class="token operator">:</span> <span class="token number">0.2</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>注意</strong>：extrudePolygon 和 <a href="https://doc.babylonjs.com/divingDeeper/mesh/creation/param/polyMeshBuilder" target="_blank" rel="noopener noreferrer">PolygonMeshBuilder<ExternalLinkIcon/></a> 都使用<em>earcut slicing</em>算法。
Playground 已经定义了 earcut，但是如果在自己的文件系统上按本教程做，则需要通过 <a href="https://unpkg.com/earcut@latest/dist/earcut.min.js" target="_blank" rel="noopener noreferrer">cdn<ExternalLinkIcon/></a> 或 <a href="https://github.com/mapbox/earcut#install" target="_blank" rel="noopener noreferrer">npm<ExternalLinkIcon/></a> 下载 earcut 算法。
如果使用 TypeScript，可以将 Earcut 算法通过 <a href="https://doc.babylonjs.com/typedoc/classes/babylon.meshbuilder#extrudepolygon" target="_blank" rel="noopener noreferrer">extudePolygon 函数<ExternalLinkIcon/></a>上的 <em>earcutInjection</em> 参数注入。</p>
<p>创建轮子过程，略。该<a href="https://playground.babylonjs.com/#KDPAQ9#11" target="_blank" rel="noopener noreferrer">示例代码<ExternalLinkIcon/></a>。</p>
<p><a href="https://doc.babylonjs.com/start/chap3/polycar" target="_blank" rel="noopener noreferrer">https://doc.babylonjs.com/start/chap3/polycar<ExternalLinkIcon/></a></p>
</template>
