<template><h1 id="车轮动画" tabindex="-1"><a class="header-anchor" href="#车轮动画" aria-hidden="true">#</a> 车轮动画</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#动画基础">动画基础</RouterLink></li></ul></nav>
<h2 id="动画基础" tabindex="-1"><a class="header-anchor" href="#动画基础" aria-hidden="true">#</a> 动画基础</h2>
<p>我们要实现车轮沿轴旋转的动画。</p>
<p>首先创建动画对象。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> animWheel <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Animation</span><span class="token punctuation">(</span><span class="token string">"wheelAnimation"</span><span class="token punctuation">,</span> <span class="token string">"rotation.y"</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Animation<span class="token punctuation">.</span><span class="token constant">ANIMATIONTYPE_FLOAT</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Animation<span class="token punctuation">.</span><span class="token constant">ANIMATIONLOOPMODE_CYCLE</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>动画对象包含以下参数：名称，属性，帧率，循环模式。</p>
<p>设置关键帧：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> wheelKeys <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span> 

<span class="token comment">//At the animation key 0, the value of rotation.y is 0</span>
wheelKeys<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">frame</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
    <span class="token literal-property property">value</span><span class="token operator">:</span> <span class="token number">0</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//At the animation key 30, (after 1 sec since animation fps = 30) the value of rotation.y is 2PI for a complete rotation</span>
wheelKeys<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">frame</span><span class="token operator">:</span> <span class="token number">30</span><span class="token punctuation">,</span>
    <span class="token literal-property property">value</span><span class="token operator">:</span> <span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>将关键帧连接到动画对象：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//set the keys</span>
animWheel<span class="token punctuation">.</span><span class="token function">setKeys</span><span class="token punctuation">(</span>wheelKeys<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//Link this animation to the right back wheel</span>
wheelRB<span class="token punctuation">.</span>animations <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
wheelRB<span class="token punctuation">.</span>animations<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>animWheel<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//Begin animation - 动画物体, 开始帧，结束帧，是否循环</span>
scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelRB<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>同样的动画应用到其它轮子：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelRF<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelLB<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelLF<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KDPAQ9#14" target="_blank" rel="noopener noreferrer">轮子动画单独<ExternalLinkIcon/></a></p>
<p>优化代码，将汽车的模型和动画导出为单独的模块：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">ImportMeshAsync</span><span class="token punctuation">(</span><span class="token string">""</span><span class="token punctuation">,</span> <span class="token string">"url to model car"</span><span class="token punctuation">,</span> <span class="token string">"car.babylon"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span>  <span class="token punctuation">{</span>
    <span class="token keyword">const</span> wheelRB <span class="token operator">=</span> scene<span class="token punctuation">.</span><span class="token function">getMeshByName</span><span class="token punctuation">(</span><span class="token string">"wheelRB"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> wheelRF <span class="token operator">=</span> scene<span class="token punctuation">.</span><span class="token function">getMeshByName</span><span class="token punctuation">(</span><span class="token string">"wheelRF"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> wheelLB <span class="token operator">=</span> scene<span class="token punctuation">.</span><span class="token function">getMeshByName</span><span class="token punctuation">(</span><span class="token string">"wheelLB"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> wheelLF <span class="token operator">=</span> scene<span class="token punctuation">.</span><span class="token function">getMeshByName</span><span class="token punctuation">(</span><span class="token string">"wheelLF"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelRB<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelRF<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelLB<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>wheelLF<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KDPAQ9#15" target="_blank" rel="noopener noreferrer">轮子动画完整<ExternalLinkIcon/></a></p>
</template>
