<template><h1 id="角色动画" tabindex="-1"><a class="header-anchor" href="#角色动画" aria-hidden="true">#</a> 角色动画</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#角色行走动画">角色行走动画</RouterLink></li></ul></nav>
<h2 id="角色行走动画" tabindex="-1"><a class="header-anchor" href="#角色行走动画" aria-hidden="true">#</a> 角色行走动画</h2>
<p><img src="https://doc.babylonjs.com/img/getstarted/dude.gif" alt=""></p>
<p>导入一个带绑定和动画的角色</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneLoader<span class="token punctuation">.</span><span class="token function">ImportMeshAsync</span><span class="token punctuation">(</span><span class="token string">"mesh name"</span><span class="token punctuation">,</span> <span class="token string">"path to model"</span><span class="token punctuation">,</span> <span class="token string">"model file"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">result</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> dude <span class="token operator">=</span> result<span class="token punctuation">.</span>meshes<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    dude<span class="token punctuation">.</span>scaling <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0.25</span><span class="token punctuation">,</span> <span class="token number">0.25</span><span class="token punctuation">,</span> <span class="token number">0.25</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                
    scene<span class="token punctuation">.</span><span class="token function">beginAnimation</span><span class="token punctuation">(</span>result<span class="token punctuation">.</span>skeletons<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token number">1.0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#SFW46K#1" target="_blank" rel="noopener noreferrer">角色动画<ExternalLinkIcon/></a></p>
</template>
