<template><h1 id="行走在村庄" tabindex="-1"><a class="header-anchor" href="#行走在村庄" aria-hidden="true">#</a> 行走在村庄</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#行走在村庄-1">行走在村庄</RouterLink></li></ul></nav>
<h2 id="行走在村庄-1" tabindex="-1"><a class="header-anchor" href="#行走在村庄-1" aria-hidden="true">#</a> 行走在村庄</h2>
<p>网格有一个 movePOV 方法，它可以相对于其朝向移动网格。通常，新建网格朝向 -z 方向。要将网格沿其朝向向移动 6 个单位，请使用</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mesh<span class="token punctuation">.</span><span class="token function">movePOV</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>参数分别是向右、向上和向前移动的距离，通常这些是网格局部空间中的 -x 轴、y 轴和 -z 轴。</p>
<p>在 Babylon.js 中，渲染下一帧之前可以使用如下代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>onBeforeRenderObservable<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token comment">//code to execute</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这样，物体的属性可以逐帧地改变。</p>
<p>下面的代码可以实现一个简单的路径动画。我们让小球沿三角形（边长为4的等腰直角三角形）的边运动</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> sphere <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateSphere</span><span class="token punctuation">(</span><span class="token string">"sphere"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">diameter</span><span class="token operator">:</span> <span class="token number">0.25</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//end points for the line sequence in an array</span>
<span class="token comment">//y component can be non zero</span>
<span class="token keyword">const</span> points <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
points<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
points<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
points<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
points<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>points<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//close the triangle;</span>

<span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateLines</span><span class="token punctuation">(</span><span class="token string">"triangle"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">points</span><span class="token operator">:</span> points<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>另外，我们介绍另一种控制物体旋转的方法，代码如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mesh<span class="token punctuation">.</span><span class="token function">rotate</span><span class="token punctuation">(</span>axis<span class="token punctuation">,</span> angle<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Space<span class="token punctuation">.</span><span class="token constant">LOCAL</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>为了在每个渲染帧之前生成动画，球体将移动 0.05 的距离。当它行进的距离大于 4 时，球体将转动，大于 8 时它将再次转动，当大于周长时，它将重置并重新开始。</p>
<p>我们使用属性 turn 和 distance 设置了一个跟踪对象数组。在行进指定的总距离后，球体将旋转指定的转弯值。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token function-variable function">slide</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">turn<span class="token punctuation">,</span> dist</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">//after covering dist apply turn</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>turn <span class="token operator">=</span> turn<span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>dist <span class="token operator">=</span> dist<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> track <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
track<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">slide</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// 第1条边长 4</span>
track<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">slide</span><span class="token punctuation">(</span><span class="token number">3</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 加上第2条边长，结果是4+4=8</span>
track<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">slide</span><span class="token punctuation">(</span><span class="token number">3</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">8</span> <span class="token operator">+</span> <span class="token number">4</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">sqrt</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 加上第3条边，周长为8 + Math.sqrt(4+4)))</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>每当达到所需距离时，就进行一次转弯，数组索引指针 p 增加 1。模运算符 % 用于在数组末尾将指针重置为零。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>distance <span class="token operator">></span> track<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">.</span>dist<span class="token punctuation">)</span> <span class="token punctuation">{</span>        
    sphere<span class="token punctuation">.</span><span class="token function">rotate</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>Axis<span class="token punctuation">.</span><span class="token constant">Y</span><span class="token punctuation">,</span> track<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">.</span>turn<span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Space<span class="token punctuation">.</span><span class="token constant">LOCAL</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    p <span class="token operator">+=</span><span class="token number">1</span><span class="token punctuation">;</span>
    p <span class="token operator">%=</span> track<span class="token punctuation">.</span>length<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为防止累积浮点错误，每当索引指针重置为 0 时，球体的位置和旋转也会重置</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>p <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    distance <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    sphere<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//reset to initial conditions</span>
    sphere<span class="token punctuation">.</span>rotation <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Zero</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//prevents error accumulation </span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#N9IZ8M#1" target="_blank" rel="noopener noreferrer">小球沿三角形的边运动<ExternalLinkIcon/></a></p>
<p>控制角色在村庄行走稍微有点棘手，需要在转弯和距离上反复试验。在旋转方法中使用度数并将其转换为弧度的原因之一是通过添加一两个度数更容易进行调整。</p>
<p>由于从 .babylon 文件导入的角色 dude 已经使用 rotationQuaternion 而不是旋转设置了其旋转，我们使用 rotate 方法来重置角色方向。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>dude<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
dude<span class="token punctuation">.</span><span class="token function">rotate</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>Axis<span class="token punctuation">.</span><span class="token constant">Y</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Tools<span class="token punctuation">.</span><span class="token function">ToRadians</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">95</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Space<span class="token punctuation">.</span><span class="token constant">LOCAL</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> startRotation <span class="token operator">=</span> dude<span class="token punctuation">.</span>rotationQuaternion<span class="token punctuation">.</span><span class="token function">clone</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//use clone so that variables are independent not linked copies</span>

<span class="token keyword">if</span> <span class="token punctuation">(</span>p <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    distance <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    dude<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    dude<span class="token punctuation">.</span>rotationQuaternion <span class="token operator">=</span> startRotation<span class="token punctuation">.</span><span class="token function">clone</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KBS9I5#81" target="_blank" rel="noopener noreferrer">角色行走动画<ExternalLinkIcon/></a></p>
</template>
