<template><h1 id="背景材质-backgroundmaterial" tabindex="-1"><a class="header-anchor" href="#背景材质-backgroundmaterial" aria-hidden="true">#</a> 背景材质 BackgroundMaterial</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#介绍">介绍</RouterLink></li><li><RouterLink to="#漫反射-diffuse">漫反射 Diffuse</RouterLink><ul><li><RouterLink to="#阴影-shadows">阴影 Shadows</RouterLink></li><li><RouterLink to="#不透明度-opacity">不透明度 Opacity</RouterLink></li><li><RouterLink to="#不透明度菲涅尔-opacity-fresnel">不透明度菲涅尔 Opacity Fresnel</RouterLink></li></ul></li><li><RouterLink to="#反射-reflection">反射 Reflection</RouterLink><ul><li><RouterLink to="#镜面-mirror">镜面 Mirror</RouterLink></li><li><RouterLink to="#反射菲涅尔-reflection-fresnel">反射菲涅尔 Reflection Fresnel</RouterLink></li></ul></li><li><RouterLink to="#杂项和颜色">杂项和颜色</RouterLink></li></ul></nav>
<h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍" aria-hidden="true">#</a> 介绍</h2>
<p>由于在一个场景中并不总是需要可以照亮的材质。我们正在引入一种新的无光和快速的材质，以解决在使用标准或PBR材质时可能遇到的限制。</p>
<p>背景材质 BackgroundMaterial 是完全无光的，但仍然可以接受阴影或受到图片处理信息的影响。这使得它最适合作为天空盒或地面材质使用。</p>
<h2 id="漫反射-diffuse" tabindex="-1"><a class="header-anchor" href="#漫反射-diffuse" aria-hidden="true">#</a> 漫反射 Diffuse</h2>
<p>漫反射部分用于简单地为网格赋予颜色。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"textures/grass.jpg"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#157MGZ" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之漫反射<ExternalLinkIcon/></a></p>
<h3 id="阴影-shadows" tabindex="-1"><a class="header-anchor" href="#阴影-shadows" aria-hidden="true">#</a> 阴影 Shadows</h3>
<p>这种材质尽管没有被照亮，但能够接受阴影。这实际上是它的一个优势，使适合用于地面。如果你想减少阴影的数量，可以使用专用的属性：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>shadowLevel <span class="token operator">=</span> <span class="token number">0.4</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#3" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之阴影<ExternalLinkIcon/></a></p>
<p>从Babylonjs v4.2开始，新增了一个新的<code v-pre>shadowOnly</code>属性，只渲染阴影，使材质的行为类似于<code v-pre>ShadowOnlyMaterial</code>材质，但没有单一光线的限制。</p>
<p>当<code v-pre>shadowOnly = true</code>时，可以用<code v-pre>primaryColor</code>来对阴影的颜色和alpha进行着色，以使阴影变得更强或更弱。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>primaryColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color4</span><span class="token punctuation">(</span><span class="token number">0.6</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>shadowOnly <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#33" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之阴影颜色<ExternalLinkIcon/></a></p>
<h3 id="不透明度-opacity" tabindex="-1"><a class="header-anchor" href="#不透明度-opacity" aria-hidden="true">#</a> 不透明度 Opacity</h3>
<p>如果你想做一个透明的地面，而漫反射纹理带有透明通道，可使用如下代码：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>diffuseTexture<span class="token punctuation">.</span>hasAlpha <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#149" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之透明地面<ExternalLinkIcon/></a></p>
<h3 id="不透明度菲涅尔-opacity-fresnel" tabindex="-1"><a class="header-anchor" href="#不透明度菲涅尔-opacity-fresnel" aria-hidden="true">#</a> 不透明度菲涅尔 Opacity Fresnel</h3>
<p>此外，默认情况下，当眼睛接近与地面平齐时，地面会消失。这可以防止这种角度下地面变成一条硬的直线。可以通过以下方式禁用它：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>opacityFresnel <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span> <span class="token comment">// 默认true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#5" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之不透明度菲涅尔<ExternalLinkIcon/></a></p>
<h2 id="反射-reflection" tabindex="-1"><a class="header-anchor" href="#反射-reflection" aria-hidden="true">#</a> 反射 Reflection</h2>
<p>无光材质非常适合创建天空盒。你可以像使用标准材质一样设置反射纹理：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>CubeTexture</span><span class="token punctuation">(</span><span class="token string">"textures/TropicalSunnyDay"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>reflectionTexture<span class="token punctuation">.</span>coordinatesMode <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Texture<span class="token punctuation">.</span><span class="token constant">SKYBOX_MODE</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#150" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之反射纹理（蓝天环境）<ExternalLinkIcon/></a></p>
<h3 id="镜面-mirror" tabindex="-1"><a class="header-anchor" href="#镜面-mirror" aria-hidden="true">#</a> 镜面 Mirror</h3>
<p>由于可以将反射与标准材料进行比较，因此使用镜子的工作方式也相同。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> mirror <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>MirrorTexture</span><span class="token punctuation">(</span><span class="token string">"mirror"</span><span class="token punctuation">,</span> <span class="token number">512</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
mirror<span class="token punctuation">.</span>mirrorPlane <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Plane</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
mirror<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>

backgroundMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> mirror<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#9" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之镜面纹理<ExternalLinkIcon/></a></p>
<h3 id="反射菲涅尔-reflection-fresnel" tabindex="-1"><a class="header-anchor" href="#反射菲涅尔-reflection-fresnel" aria-hidden="true">#</a> 反射菲涅尔 Reflection Fresnel</h3>
<p>由于我们可以同时使用反射和漫反射，反射菲涅尔可以实现更沉浸式的体验：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> backgroundMaterial <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>BackgroundMaterial</span><span class="token punctuation">(</span><span class="token string">"backgroundMaterial"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"https://assets.babylonjs.com/environments/backgroundGround.png"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>diffuseTexture<span class="token punctuation">.</span>hasAlpha <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>opacityFresnel <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>shadowLevel <span class="token operator">=</span> <span class="token number">0.4</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> mirror <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>MirrorTexture</span><span class="token punctuation">(</span><span class="token string">"mirror"</span><span class="token punctuation">,</span> <span class="token number">512</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
mirror<span class="token punctuation">.</span>mirrorPlane <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Plane</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
mirror<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>sphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> mirror<span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>reflectionFresnel <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>reflectionStandardFresnelWeight <span class="token operator">=</span> <span class="token number">0.8</span><span class="token punctuation">;</span>

ground<span class="token punctuation">.</span>material <span class="token operator">=</span> backgroundMaterial<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#10" target="_blank" rel="noopener noreferrer">BackgroundMaterial材质之反射菲涅尔<ExternalLinkIcon/></a></p>
<h2 id="杂项和颜色" tabindex="-1"><a class="header-anchor" href="#杂项和颜色" aria-hidden="true">#</a> 杂项和颜色</h2>
<p>由于有时我们只需要颜色，你可以把纹理作为灰色比例的信息来与颜色混合。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>backgroundMaterial<span class="token punctuation">.</span>useRGBColor <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
backgroundMaterial<span class="token punctuation">.</span>primaryColor <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Magenta</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#G3HSAW#11" target="_blank" rel="noopener noreferrer">混合灰度和颜色<ExternalLinkIcon/></a></p>
</template>
