<template><h1 id="环境介绍" tabindex="-1"><a class="header-anchor" href="#环境介绍" aria-hidden="true">#</a> 环境介绍</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#如何实现">如何实现？</RouterLink><ul><li><RouterLink to="#改变背景色-scene-clearcolor">改变背景色 scene.clearColor</RouterLink></li><li><RouterLink to="#改变环境色-scene-ambientcolor">改变环境色 scene.ambientColor</RouterLink></li><li><RouterLink to="#天空盒-skybox">天空盒 Skybox</RouterLink></li></ul></li><li><RouterLink to="#雾-fog">雾 Fog</RouterLink></li></ul></nav>
<p>如何为你的游戏或应用实现一个良好的、适当的真实环境呢？我们将从简单的场景<code v-pre>clearColor</code>（背景色）开始，然后简单谈谈场景<code v-pre>ambientColor</code>，接着是6纹理的天空盒 skybox，然后是能给场景带来深度感的雾 fog。</p>
<h2 id="如何实现" tabindex="-1"><a class="header-anchor" href="#如何实现" aria-hidden="true">#</a> 如何实现？</h2>
<p>我们很快就会谈及这种漂亮的雾效。首先，介绍一下<a href="https://doc.babylonjs.com/typedoc/classes/babylon.scene" target="_blank" rel="noopener noreferrer">场景类对象<ExternalLinkIcon/></a>的两个有趣的属性。</p>
<ul>
<li><code v-pre>scene.clearColor</code> - 改变 &quot;背景&quot; 的颜色。</li>
<li><code v-pre>scene.ambientColor</code> - 改变多个效果中使用的颜色，包括环境照明。</li>
</ul>
<p>两者都非常有用，而且本身就很强大。</p>
<h3 id="改变背景色-scene-clearcolor" tabindex="-1"><a class="header-anchor" href="#改变背景色-scene-clearcolor" aria-hidden="true">#</a> 改变背景色 scene.clearColor</h3>
<p>场景 Scene 对象上的'clearColor'属性是最基本的环境属性/调整。简单地说，就是如何改变场景的背景颜色。下面是它的操作方法。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>clearColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0.5</span><span class="token punctuation">,</span> <span class="token number">0.8</span><span class="token punctuation">,</span> <span class="token number">0.5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>或者使用预设颜色，从而避免使用<code v-pre>New</code>关键词。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>clearColor <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Color3<span class="token punctuation">.</span><span class="token function">Blue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>这个颜色和属性不用于网格、材质、纹理或其他任何东西的最终颜色的计算。它只是单纯的场景的背景色。</p>
<h3 id="改变环境色-scene-ambientcolor" tabindex="-1"><a class="header-anchor" href="#改变环境色-scene-ambientcolor" aria-hidden="true">#</a> 改变环境色 scene.ambientColor</h3>
<p>相反，场景对象上的<code v-pre>ambientColor</code>属性是一个非常强大和有影响力的环境属性/调整。首先，让我们看一下它的语法。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>ambientColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0.3</span><span class="token punctuation">,</span> <span class="token number">0.3</span><span class="token punctuation">,</span> <span class="token number">0.3</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如你所见，它的设置格式与clearColor相同，但是ambientColor在确定场景元素的最终颜色时，会用到很多的计算。主要是与网格的<code v-pre>StandardMaterial.ambientColor</code>结合使用，以确定网格材质的最终环境色。</p>
<p>你会发现，当没有<code v-pre>scene.ambientColor</code>时，<code v-pre>StandardMaterial.ambientColor</code>和<code v-pre>StandardMaterial.ambientTexture</code>不会起任何作用。设置一个scene.ambientColor的值，就像上面的例子一样，<code v-pre>StandardMaterial.ambientColor / StandardMaterial.ambientTexture</code> 就会在你应用了这样的网格上发挥作用。</p>
<p>默认情况下，scene.ambientColor 设置为 Color3(0, 0, 0)，也就是没有scene.ambientColor。</p>
<h3 id="天空盒-skybox" tabindex="-1"><a class="header-anchor" href="#天空盒-skybox" aria-hidden="true">#</a> 天空盒 Skybox</h3>
<p>为了营造出美丽晴朗天空的完美错觉，我们将创建一个简单的盒子，但具有特殊的纹理。有两种方法可以创建天空盒。让我们从手动开始，了解幕后的工作原理，然后我们使用自动的方式。</p>
<h4 id="手动创建" tabindex="-1"><a class="header-anchor" href="#手动创建" aria-hidden="true">#</a> 手动创建</h4>
<p>首先，我们的盒子，没什么新鲜的，只需注意禁用的<a href="https://en.wikipedia.org/wiki/Back-face_culling" target="_blank" rel="noopener noreferrer">背面剔除<ExternalLinkIcon/></a>：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> skybox <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Mesh<span class="token punctuation">.</span><span class="token function">CreateBox</span><span class="token punctuation">(</span><span class="token string">"skyBox"</span><span class="token punctuation">,</span> <span class="token number">100.0</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> skyboxMaterial <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"skyBox"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>backFaceCulling <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>disableLighting <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
skybox<span class="token punctuation">.</span>material <span class="token operator">=</span> skyboxMaterial<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>接下来，设置 <code v-pre>infiniteDistance</code> 属性。这使得天空盒跟随相机位置。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>skybox<span class="token punctuation">.</span>infiniteDistance <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>现在，必须去除盒子上的所有光线反射（太阳不会反射到天空上！）。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>skyboxMaterial<span class="token punctuation">.</span>disableLighting <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>接下来，将特殊的天空纹理应用到它上面。此纹理必须已准备好成为天空盒，位于专用目录中，在我们的示例中名为“skybox”：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>skyboxMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>CubeTexture</span><span class="token punctuation">(</span><span class="token string">"textures/skybox"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>reflectionTexture<span class="token punctuation">.</span>coordinatesMode <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Texture<span class="token punctuation">.</span><span class="token constant">SKYBOX_MODE</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>在/skybox目录中，必须存在6张天空纹理，为盒子的每个面各提供1张。每张图片必须按照相应的面来命名。&quot;skybox_nx.jpg&quot;（左），&quot;skybox_ny.jpg&quot;（下），&quot;skybox_nz.jpg&quot;（后），&quot;skybox_px.jpg&quot;（右），&quot;skybox_py.jpg&quot;（上），&quot;skybox_pz.jpg&quot;（前）。</p>
<p>也可以使用dds文件用于天空盒。这些特殊文件可以包含设置立方体纹理所需的所有信息。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>skyboxMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>CubeTexture</span><span class="token punctuation">(</span><span class="token string">"/assets/textures/SpecularHDR.dds"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>最后要注意的是，如果你想让天空盒渲染在其他所有物体的后面，请将天空盒的 <code v-pre>renderGroupId</code> 设置为 0，并将所有其他可渲染对象的 <code v-pre>renderGroupId</code> 设置为大于零，例如：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>skybox<span class="token punctuation">.</span>renderingGroupId <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>

<span class="token comment">// Some other mesh</span>
myMesh<span class="token punctuation">.</span>renderingGroupId <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://doc.babylonjs.com/divingDeeper/materials/advanced/transparent_rendering" target="_blank" rel="noopener noreferrer">点此<ExternalLinkIcon/></a>查看有关渲染组和渲染顺序的更多信息。</p>
<h4 id="自动创建" tabindex="-1"><a class="header-anchor" href="#自动创建" aria-hidden="true">#</a> 自动创建</h4>
<p>我们了解了如何创建天空盒，现在我们改用一种更简单的方法：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> envTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>CubeTexture</span><span class="token punctuation">(</span><span class="token string">"/assets/textures/SpecularHDR.dds"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span><span class="token function">createDefaultSkybox</span><span class="token punctuation">(</span>envTexture<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#BH23ZD#1" target="_blank" rel="noopener noreferrer">天空盒助手示例<ExternalLinkIcon/></a></p>
<p>查看<RouterLink to="/babylonjs/divingDeeper/scene/fastBuildWorld.html#%E7%8E%AF%E5%A2%83%E5%8A%A9%E6%89%8B">场景助手</RouterLink>以获取有关此助手和其他助手的更多信息。</p>
<h2 id="雾-fog" tabindex="-1"><a class="header-anchor" href="#雾-fog" aria-hidden="true">#</a> 雾 Fog</h2>
<p>雾是一种相当高级的效果，但Babylon.js中的雾已经被最大限度地简化了。现在在场景中添加雾非常容易。首先，我们像这样定义雾的模式。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>fogMode <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Scene<span class="token punctuation">.</span><span class="token constant">FOGMODE_EXP</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>以下是可用的模式：</p>
<ul>
<li>BABYLON.Scene.FOGMODE_NONE - 默认值，禁用雾。</li>
<li>BABYLON.Scene.FOGMODE_EXP - 雾的密度按照指数函数计算。</li>
<li>BABYLON.Scene.FOGMODE_EXP2 - 和上面一样，但速度更快。</li>
<li>BABYLON.Scene.FOGMODE_LINEAR - 雾的密度按照线性函数计算。</li>
</ul>
<p>如果选择 EXP 或 EXP2 模式，则可以定义密度选项（默认为 0.1）：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>fogDensity <span class="token operator">=</span> <span class="token number">0.01</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>否则，如果选择 LINEAR 模式，那么可以定义雾从哪里开始，从哪里结束：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>fogStart <span class="token operator">=</span> <span class="token number">20.0</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span>fogEnd <span class="token operator">=</span> <span class="token number">60.0</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>最后，无论哪种模式，都可以指定雾的颜色（默认为 BABYLON.Color3(0.2, 0.2, 0.3)）：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>scene<span class="token punctuation">.</span>fogColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0.9</span><span class="token punctuation">,</span> <span class="token number">0.9</span><span class="token punctuation">,</span> <span class="token number">0.85</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#7G0IQW" target="_blank" rel="noopener noreferrer">雾示例<ExternalLinkIcon/></a></p>
</template>
