<template><h1 id="反射探头-reflectionprobe" tabindex="-1"><a class="header-anchor" href="#反射探头-reflectionprobe" aria-hidden="true">#</a> 反射探头 ReflectionProbe</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#探头和pbr">探头和PBR</RouterLink></li></ul></nav>
<p>反射探头用于动态生成立方体贴图，例如可以用作反射纹理。</p>
<p>用法如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> probe <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ReflectionProbe</span><span class="token punctuation">(</span><span class="token string">"main"</span><span class="token punctuation">,</span> <span class="token number">512</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
probe<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>yellowSphere<span class="token punctuation">)</span><span class="token punctuation">;</span>
probe<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>greenSphere<span class="token punctuation">)</span><span class="token punctuation">;</span> 
probe<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>blueSphere<span class="token punctuation">)</span><span class="token punctuation">;</span>  
probe<span class="token punctuation">.</span>renderList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>mirror<span class="token punctuation">)</span><span class="token punctuation">;</span>  

mainMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> probe<span class="token punctuation">.</span>cubeTexture<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>正如你所见，必须定义哪些网格会被反射探头渲染。</p>
<p><strong>必须谨慎对待反射探头，因为它们实际上需要每帧生成6个纹理（每个面一个）。</strong></p>
<p>可以用这段代码改变更新率（默认为每帧）。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>probe<span class="token punctuation">.</span>refreshRate <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>RenderTargetTexture<span class="token punctuation">.</span><span class="token constant">REFRESHRATE_RENDER_ONCE</span><span class="token punctuation">;</span>    
<span class="token comment">// or</span>
probe<span class="token punctuation">.</span>refreshRate <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>RenderTargetTexture<span class="token punctuation">.</span><span class="token constant">REFRESHRATE_RENDER_ONEVERYFRAME</span><span class="token punctuation">;</span>    
<span class="token comment">// or</span>
probe<span class="token punctuation">.</span>refreshRate <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>RenderTargetTexture<span class="token punctuation">.</span><span class="token constant">REFRESHRATE_RENDER_ONEVERYTWOFRAMES</span><span class="token punctuation">;</span>
<span class="token comment">// or</span>
probe<span class="token punctuation">.</span>refreshRate <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为了获得最佳的渲染效果，还需要将探头移动到要生成立方体贴图的网格的中心位置。(在内部，探头会在特定的位置生成一个虚拟摄像机，然后从那里开始渲染各个面）。你有两个选择来实现这一点：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>probe<span class="token punctuation">.</span><span class="token function">attachToMesh</span><span class="token punctuation">(</span>root<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// or</span>
probe<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KA93U#243" target="_blank" rel="noopener noreferrer">反射探头示例<ExternalLinkIcon/></a></p>
<h2 id="探头和pbr" tabindex="-1"><a class="header-anchor" href="#探头和pbr" aria-hidden="true">#</a> 探头和PBR</h2>
<p>如果想让PBR材质使用探头实现最高质量的实时反射，引擎需要额外的处理来实现正确的光泽度/粗糙度效果。要做到这一点其实很简单，首先在网格上用PBR材质设置一个探头，如上一段所述。然后在材质上启用这个标志：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mainMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> probe<span class="token punctuation">.</span>cubeTexture<span class="token punctuation">;</span>
mainMaterial<span class="token punctuation">.</span>realTimeFiltering <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>这个标志将确保PBR材质能够正确地用探头渲染。然而，这个标志涉及到材质的更多GPU处理，所以一定要明智地使用它。为了控制性能，可以设置材质的过滤过程的质量。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mainMaterial<span class="token punctuation">.</span>realTimeFilteringQuality <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Constants<span class="token punctuation">.</span><span class="token constant">TEXTURE_FILTERING_QUALITY_MEDIUM</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>默认是 TEXTURE_FILTERING_QUALITY_LOW。试试不同的质量，看看对你的场景来说什么是最好的性能/质量权衡。</p>
<p><a href="https://playground.babylonjs.com/#FEEK7G#116" target="_blank" rel="noopener noreferrer">反射探头和PBR示例<ExternalLinkIcon/></a></p>
</template>
