<template><h1 id="记录场景修改" tabindex="-1"><a class="header-anchor" href="#记录场景修改" aria-hidden="true">#</a> 记录场景修改</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#记录修改">记录修改</RouterLink></li><li><RouterLink to="#示例">示例</RouterLink></li><li><RouterLink to="#使用查看器-inspector">使用查看器 Inspector</RouterLink></li><li><RouterLink to="#限制">限制</RouterLink></li></ul></nav>
<p>从Babylon.js v4.2开始，可以对一个场景使用增量修改。这意味着你可以&quot;记录&quot;对一个场景所做的所有修改，并在以后重新应用这些修改。</p>
<p>当你从一个.babylon或.gltf文件中加载一个场景，并且你想对它进行修改时，这一点特别有用（无需从你的DCC工具中重新导出场景）。</p>
<h2 id="记录修改" tabindex="-1"><a class="header-anchor" href="#记录修改" aria-hidden="true">#</a> 记录修改</h2>
<p>要记录对一个场景所做的修改，只需创建一个新的<code v-pre>SceneRecorder</code>并调用它的<code v-pre>track()</code>函数。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> recorder <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SceneRecorder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

recorder<span class="token punctuation">.</span><span class="token function">track</span><span class="token punctuation">(</span>scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>返回的值是一个JSON对象，你可以下载或以后再使用。</p>
<p>要下载它，你可以利用工具类。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>Tools<span class="token punctuation">.</span><span class="token function">Download</span><span class="token punctuation">(</span><span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>delta<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"delta.json"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如果你想把它应用于你的场景，你可以调用<code v-pre>ApplyDelta</code>静态方法。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneRecorder<span class="token punctuation">.</span><span class="token function">ApplyDelta</span><span class="token punctuation">(</span>delta<span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="示例" tabindex="-1"><a class="header-anchor" href="#示例" aria-hidden="true">#</a> 示例</h2>
<p>让我们看一个例子来看看它的实际效果：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> scene <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Scene</span><span class="token punctuation">(</span>engine<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> camera <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>FreeCamera</span><span class="token punctuation">(</span><span class="token string">"camera1"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
camera<span class="token punctuation">.</span><span class="token function">setTarget</span><span class="token punctuation">(</span><span class="token constant">BABYLON</span><span class="token punctuation">.</span>Vector3<span class="token punctuation">.</span><span class="token function">Zero</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
camera<span class="token punctuation">.</span><span class="token function">attachControl</span><span class="token punctuation">(</span>canvas<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> light <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HemisphericLight</span><span class="token punctuation">(</span><span class="token string">"light"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
light<span class="token punctuation">.</span>intensity <span class="token operator">=</span> <span class="token number">0.7</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> sphere <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateSphere</span><span class="token punctuation">(</span><span class="token string">"sphere"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">diameter</span><span class="token operator">:</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token literal-property property">segments</span><span class="token operator">:</span> <span class="token number">32</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
sphere<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> ground <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateGround</span><span class="token punctuation">(</span><span class="token string">"ground"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> <span class="token number">6</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Instantiate the recorder</span>
<span class="token keyword">var</span> recorder <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>SceneRecorder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

recorder<span class="token punctuation">.</span><span class="token function">track</span><span class="token punctuation">(</span>scene<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Let's make some changes</span>
sphere<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span>clearColor<span class="token punctuation">.</span>r <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>

light<span class="token punctuation">.</span>intensity <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> light2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>HemisphericLight</span><span class="token punctuation">(</span><span class="token string">"light2"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>

ground<span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Now we can get the delta file</span>
<span class="token keyword">let</span> delta <span class="token operator">=</span> recorder<span class="token punctuation">.</span><span class="token function">getDelta</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Just to see the changes, we are updating the value so we can see what the delta is doing</span>
ground <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateGround</span><span class="token punctuation">(</span><span class="token string">"ground"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> <span class="token number">6</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
light2<span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
sphere<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span>
scene<span class="token punctuation">.</span>clearColor<span class="token punctuation">.</span>r <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
light<span class="token punctuation">.</span>intensity <span class="token operator">=</span> <span class="token number">1.0</span><span class="token punctuation">;</span>

<span class="token comment">// Apply the delta</span>
<span class="token constant">BABYLON</span><span class="token punctuation">.</span>SceneRecorder<span class="token punctuation">.</span><span class="token function">ApplyDelta</span><span class="token punctuation">(</span>delta<span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#MPD4TQ#1" target="_blank" rel="noopener noreferrer">增量修改示例<ExternalLinkIcon/></a></p>
<h2 id="使用查看器-inspector" tabindex="-1"><a class="header-anchor" href="#使用查看器-inspector" aria-hidden="true">#</a> 使用查看器 Inspector</h2>
<p>你也可以使用查看器来记录delta。要做到这一点，请跳到 Tools 选项卡，选择 Replay 部分的[Start recording] 按钮。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fscene%2Finspector-record.jpg&amp;w=1920&amp;q=75" alt=""></p>
<p>完成录制后，转到同一位置并点击 [Generate delta file]：</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fscene%2Finspector-generate.jpg&amp;w=1920&amp;q=75" alt=""></p>
<p>这将把文件下载到本地。</p>
<h2 id="限制" tabindex="-1"><a class="header-anchor" href="#限制" aria-hidden="true">#</a> 限制</h2>
<p>记录器有一些限制在这里列出：</p>
<ul>
<li>它将只记录简单的值（array, colors, vectors, boolean, number）。</li>
<li>它不会记录大的状态变化，比如。
<ul>
<li>更新一个网格的材质属性</li>
<li>更新网格的骨架属性</li>
<li>更新网格的几何形状</li>
</ul>
</li>
</ul>
</template>
