<template><h1 id="环顾四周" tabindex="-1"><a class="header-anchor" href="#环顾四周" aria-hidden="true">#</a> 环顾四周</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>目前我们正在使用 ArcRotateCamera，它可以让我们从远处环绕村庄世界。从村里看风景怎么样？让我们将相机设置为角色在村子里走来走去，并通过一些调整值从他的肩膀上环顾四周。 ArcRotateCamera 的创建具有这种形式，</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> camera <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ArcRotateCamera</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> alpha angle<span class="token punctuation">,</span> beta angle<span class="token punctuation">,</span> radius<span class="token punctuation">,</span> target position<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>与所有相机一样，为了响应用户输入而移动它，我们需要将其附加到画布上。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>camera<span class="token punctuation">.</span><span class="token function">attachControl</span><span class="token punctuation">(</span>canvas<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>将此相机视为围绕其目标位置运行的相机，或者更具想象力地视为围绕地球运行的间谍卫星。其相对于目标（地球）的位置可以由三个参数设置，alpha（弧度）为纵向旋转，beta（弧度）为纬度旋转，radians 与目标位置的距离。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fhow_to%2Fcamalphabeta.jpg&amp;w=1920&amp;q=75" alt=""></p>
<p>在我们的例子中，我们想让相机成为角色的父级</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>camera<span class="token punctuation">.</span>parent <span class="token operator">=</span> dude<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>并且，因为角色的尺寸被缩放，所以我们使用一个大半径，作为角色的父级将被缩小。为了追踪他，我们使用</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> camera <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>ArcRotateCamera</span><span class="token punctuation">(</span><span class="token string">"camera"</span><span class="token punctuation">,</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2.5</span><span class="token punctuation">,</span> <span class="token number">150</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">60</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>由于角色会立即转动，因此相机也会转动。为了使观看更流畅，需要角色跟随的更流畅的轨迹。</p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#97" target="_blank" rel="noopener noreferrer">第三人称视角<ExternalLinkIcon/></a></p>
</template>
