<template><h1 id="使用高度图创建远山" tabindex="-1"><a class="header-anchor" href="#使用高度图创建远山" aria-hidden="true">#</a> 使用高度图创建远山</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>我们想把村庄建在山谷里。可以使用网格创建山丘，但是还有另一种方法可以为地面网格添加垂直高度。这是使用高度图实现的，该高度图使用灰色阴影来确定地面的高度。白色区域最高，黑色最低。这个简单的高度图</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fvillageheightmap.png&amp;w=1920&amp;q=75" alt=""></p>
<p>中间有一个大的黑色区域来容纳村庄，白色区域创造了山丘，灰色区域则是从山谷中出来的道路。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fvalley1.png&amp;w=1920&amp;q=75" alt=""></p>
<p>在这张图片中，相机被拉得更远，垂直高度被夸大了。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> largeGround <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateGroundFromHeightMap</span><span class="token punctuation">(</span><span class="token string">"largeGround"</span><span class="token punctuation">,</span> <span class="token string">"url to height map"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span><span class="token number">150</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span><span class="token number">150</span><span class="token punctuation">,</span> <span class="token literal-property property">subdivisions</span><span class="token operator">:</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token literal-property property">minHeight</span><span class="token operator">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token literal-property property">maxHeight</span><span class="token operator">:</span> <span class="token number">10</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>选项的subdivisions细分属性将地面分成 20 x 20 = 400 个部分。细分越多，高度计算的层次就越精细。 minHeight 和 maxHeight 这两个属性分别确定黑色和白色区域的垂直高度，灰色区域相应地缩放。</p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#39" target="_blank" rel="noopener noreferrer">高度图基础<ExternalLinkIcon/></a></p>
<p>我们可以用正常的方式添加纹理。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Fvalley2.png&amp;w=1920&amp;q=75" alt=""></p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#40" target="_blank" rel="noopener noreferrer">带贴图的高度图<ExternalLinkIcon/></a></p>
<p>最后，我们给村庄地面一个类似于大地面的纹理，但更清晰。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//Create Village ground</span>
<span class="token keyword">const</span> groundMat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"groundMat"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
groundMat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"url to ground texture"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
groundMat<span class="token punctuation">.</span>diffuseTexture<span class="token punctuation">.</span>hasAlpha <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> ground <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateGround</span><span class="token punctuation">(</span><span class="token string">"ground"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span><span class="token number">24</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span><span class="token number">24</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
ground<span class="token punctuation">.</span>material <span class="token operator">=</span> groundMat<span class="token punctuation">;</span>

<span class="token comment">//large ground</span>
<span class="token keyword">const</span> largeGroundMat <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"largeGroundMat"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
largeGroundMat<span class="token punctuation">.</span>diffuseTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Texture</span><span class="token punctuation">(</span><span class="token string">"url to large ground texture"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> largeGround <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateGroundFromHeightMap</span><span class="token punctuation">(</span><span class="token string">"largeGround"</span><span class="token punctuation">,</span> <span class="token string">"url to heightmap"</span><span class="token punctuation">,</span> 
    <span class="token punctuation">{</span><span class="token literal-property property">width</span><span class="token operator">:</span><span class="token number">150</span><span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span><span class="token number">150</span><span class="token punctuation">,</span> <span class="token literal-property property">subdivisions</span><span class="token operator">:</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token literal-property property">minHeight</span><span class="token operator">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token literal-property property">maxHeight</span><span class="token operator">:</span> <span class="token number">4</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
largeGround<span class="token punctuation">.</span>material <span class="token operator">=</span> largeGroundMat<span class="token punctuation">;</span>
largeGround<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token operator">-</span><span class="token number">0.01</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KBS9I5#85" target="_blank" rel="noopener noreferrer">带贴图的地面<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#86" target="_blank" rel="noopener noreferrer">将环境导出<ExternalLinkIcon/></a></p>
<p><a href="https://playground.babylonjs.com/#KBS9I5#87" target="_blank" rel="noopener noreferrer">加入汽车后的场景<ExternalLinkIcon/></a></p>
</template>
