<template><h1 id="天空盒" tabindex="-1"><a class="header-anchor" href="#天空盒" aria-hidden="true">#</a> 天空盒</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>我们可以通过将6张图片应用于大型<a href="https://doc.babylonjs.com/divingDeeper/environment/skybox" target="_blank" rel="noopener noreferrer">天空盒<ExternalLinkIcon/></a>来模拟天空的外观。 （图片比 3D 对象更容易、更快速地渲染，而且对于远距离的风景也一样好。）</p>
<p>Skybox 图片通常使用 CubeTexture 加载。 CubeTexture 的构造函数采用基本 URL 并（默认情况下）附加“_px.jpg”、“_nx.jpg”、“_py.jpg”、“_ny.jpg”、“_pz.jpg”和“_nz.jpg”以加载立方体的 +x、-x、+y、-y、+z 和 -z 面。</p>
<p>即使天空盒不是反射贴图，也必须使用<a href="https://doc.babylonjs.com/divingDeeper/materials/using/reflectionTexture" target="_blank" rel="noopener noreferrer">reflectionTexture<ExternalLinkIcon/></a> 应用立方体纹理。将坐标模式设置为 SKYBOX_MODE 会直接在立方体上绘制纹理，而不是模拟反射。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> skybox <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>MeshBuilder<span class="token punctuation">.</span><span class="token function">CreateBox</span><span class="token punctuation">(</span><span class="token string">"skyBox"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token literal-property property">size</span><span class="token operator">:</span><span class="token number">150</span><span class="token punctuation">}</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> skyboxMaterial <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>StandardMaterial</span><span class="token punctuation">(</span><span class="token string">"skyBox"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>backFaceCulling <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>reflectionTexture <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>CubeTexture</span><span class="token punctuation">(</span><span class="token string">"textures/skybox"</span><span class="token punctuation">,</span> scene<span class="token punctuation">)</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>reflectionTexture<span class="token punctuation">.</span>coordinatesMode <span class="token operator">=</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Texture<span class="token punctuation">.</span><span class="token constant">SKYBOX_MODE</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>diffuseColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
skyboxMaterial<span class="token punctuation">.</span>specularColor <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Color3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
skybox<span class="token punctuation">.</span>material <span class="token operator">=</span> skyboxMaterial<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>限制相机不移动到地平面以下。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>camera<span class="token punctuation">.</span>upperBetaLimit <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2.2</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a href="https://playground.babylonjs.com/#KBS9I5#88" target="_blank" rel="noopener noreferrer">天空盒<ExternalLinkIcon/></a></p>
</template>
