<template><h1 id="定位网格-position-a-mesh" tabindex="-1"><a class="header-anchor" href="#定位网格-position-a-mesh" aria-hidden="true">#</a> 定位网格 Position A Mesh</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#位置-position">位置 Position</RouterLink></li></ul></nav>
<h2 id="位置-position" tabindex="-1"><a class="header-anchor" href="#位置-position" aria-hidden="true">#</a> 位置 Position</h2>
<p>为了充分理解在场景中定位网格的所有方法，我们需要了解参考系。当在场景中创建一个世界时，我们使用的是<strong>世界空间 World Space</strong> 中的参考系。在Babylon.js的世界空间中，有两个水平轴，x和z，以及一个垂直的y轴，是一个左手坐标系。</p>
<p>场景中的每个网格也有自己的<strong>局部空间 Local Space</strong>。网格在创建时，其局部空间原点位于世界空间原点，其局部空间的x、y、z轴与世界空间的x、y、z轴对齐。大多数（并非全部）众所周知的模型的局部原点都在网格的中心。局部原点与网格模型的相对位置取决于其构造中使用的数据集。</p>
<p>假设一个网格在世界空间中的局部原点在 (-1, 2, 1)，那么就是说 <code v-pre>Mesh.position</code>在 (-1, 2, 1)；Babylon.js有很多方法来重置网格的位置。这些方法在下面的代码中列出。注释中显示了每种方法应用后网格在世界空间中的局部原点的位置。</p>
<p>无论网格是否被旋转过，以下情况对网格来说都是如此。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mesh<span class="token punctuation">.</span>position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//(2, 3, 4)</span>
mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span><span class="token function">addInPlace</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//(-1 + 2, 2 + 3, 1 + 4) = (1, 5, 5)</span>
mesh<span class="token punctuation">.</span><span class="token function">translate</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Space<span class="token punctuation">.</span><span class="token constant">WORLD</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//(-1 + 2, 2 + 3, 1 + 4) = (1, 5, 5)</span>

mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>x <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span> <span class="token comment">//(2, 2, 1)</span>
mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">;</span> <span class="token comment">//(2, 3, 1)</span>
mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>z <span class="token operator">=</span> <span class="token number">4</span><span class="token punctuation">;</span> <span class="token comment">//(2, 3, 4)</span>

mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>x <span class="token operator">+=</span> <span class="token number">2</span><span class="token punctuation">;</span> <span class="token comment">//(-1 + 2, 2, 1) = (1, 2, 1)</span>
mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>y <span class="token operator">+=</span> <span class="token number">3</span><span class="token punctuation">;</span> <span class="token comment">//(1, 2 + 3, 1) = (1, 5, 1)</span>
mesh<span class="token punctuation">.</span>position<span class="token punctuation">.</span>z <span class="token operator">+=</span> <span class="token number">4</span><span class="token punctuation">;</span> <span class="token comment">//(1, 5, 1 + 4) = (1, 5, 5)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以下取决于网格的方向，所以不可能给出一个结果的位置。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>mesh<span class="token punctuation">.</span><span class="token function">translate</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token constant">BABYLON</span><span class="token punctuation">.</span>Space<span class="token punctuation">.</span><span class="token constant">LOCAL</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
mesh<span class="token punctuation">.</span><span class="token function">setPositionWithLocalVector</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
mesh<span class="token punctuation">.</span><span class="token function">locallyTranslate</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BABYLON<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3.</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>position</code> 和 <code v-pre>setPositionWithLocalVector</code> 的向量是位置向量。那些用于 <code v-pre>translate</code> 、<code v-pre>localTranslate</code> 和 <code v-pre>addInPlace</code> 的是方向向量。</p>
<p>下图显示了在本地空间使用后三种方法时，网格的方向如何影响其在世界空间的最终位置。</p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Ftranslate1.png&amp;w=1920&amp;q=75" alt=""></p>
<p><img src="https://doc.babylonjs.com/_next/image?url=%2Fimg%2Fgetstarted%2Ftranslate2.png&amp;w=1920&amp;q=75" alt=""></p>
<p>给定的向量被应用在网格的局部空间，其轴随网格旋转。</p>
</template>
